---
title: "Pinniped Strandings"
output: 
  word_document: 
    reference_docx: markdownstyledoc.docx
---

```{r include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.width = 4, fig.height = 3.5)
```

```{r load packages, echo = FALSE}

# install.packages("ggmap") 
# install.packages("data.table")
#install.packages("devtools")
library(devtools)
#devtools::install_github("hadley/ggplot2")
#devtools::install_github("adletaw/captioner")
library(tidyr)
library(ggmap)
library(data.table)
library(dplyr)
library(ggplot2)
library(cowplot)
library(stats)
library(scales)
library(captioner)
library(knitr)
library(reshape2)
library(stringr)
library(magrittr)

#setwd("~/Documents/R/Strandings")

# Define PlotTheme ----
plot_theme <- function(...) {
  theme(
    #text = element_text(size = 11),
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, color = "black", size = 10), 
    axis.text = element_text(vjust = 0.5, color = "black", size = 10), 
    axis.title = element_text(size = 11),
    axis.line.y = element_line(colour = "black"), 
    axis.line.x = element_line(colour = "black"), 
    plot.background = element_rect(), 
    panel.background = element_blank(), 
    panel.grid = element_blank(), 
    legend.title = element_blank(),
    legend.key = element_blank(),
    legend.text = element_text(size = 8),
    ...)
}
# Define Function for Publication Plots
pubfigure_simple_theme <- function(...) {
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_text(vjust = 0.5, color = "black", size = 10), 
    axis.title.x = element_blank(),
    axis.line.y = element_line(colour = "black"), 
    axis.line.x = element_line(colour = "black"), 
    plot.background = element_rect(), 
    panel.background = element_blank(), 
    panel.grid = element_blank(),
    legend.title = element_blank(),
    legend.key = element_blank(),
    legend.text = element_text(size = 5.5),
    ...)
}

# Define Plot Theme
pubfigure_theme <- function(...) {
  theme(
    #text = element_text(size = 11),
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, color = "black", size = 10),
    axis.text.y = element_text(vjust = 0.5, color = "black", size = 10), 
    axis.title = element_text(size = 10),
    axis.line.y = element_line(colour = "black"), 
    axis.line.x = element_line(colour = "black"), 
    plot.background = element_rect(), 
    panel.background = element_blank(), 
    panel.grid = element_blank(), 
    legend.title = element_blank(),
    legend.key = element_blank(),
    legend.text = element_text(size = 5.5),
    ...)
}

pubfigure_simple_theme <- function(...) {
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_text(vjust = 0.5, color = "black", size = 10), 
    axis.title.x = element_blank(),
    axis.line.y = element_line(colour = "black"), 
    axis.line.x = element_line(colour = "black"), 
    plot.background = element_rect(), 
    panel.background = element_blank(), 
    panel.grid = element_blank(),
    legend.title = element_blank(),
    legend.key = element_blank(),
    legend.text = element_text(size = 5.5),
    ...)
}

pubfigure_theme <- function(...) {
  theme(
    #text = element_text(size = 11),
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, color = "black", size = 10),
    axis.text.y = element_text(vjust = 0.5, color = "black", size = 10), 
    axis.title = element_text(size = 10),
    axis.line.y = element_line(colour = "black"), 
    axis.line.x = element_line(colour = "black"), 
    plot.background = element_rect(), 
    panel.background = element_blank(), 
    panel.grid = element_blank(), 
    legend.title = element_blank(),
    legend.key = element_blank(),
    legend.text = element_text(size = 5.5),
    ...)
}
case <- function(x)
  paste0(toupper(substr(x, 1, 1)), tolower(substring(x, 2)))

figs <- captioner(prefix="Figure")
tbls <- captioner(prefix="Table")

# figs("name")
# ## [1] "Figure  1: Caption."
# 
# figs("name",display="cite")
# ## [1] "Figure  1"
# 
# figs("name",display="num")
# ## [1] "1"

```

```{r load pre-cleaned csv for laptop, echo = FALSE}

pinnipeds.data <- read.csv("pinnipeds.data.csv", header = TRUE, na.strings = "", stringsAsFactors = FALSE)

pinnipeds.data$Age.Class <- factor(pinnipeds.data$Age.Class, 
          levels = c("Pup", "Yearling", "Subadult", "Adult", "Unid"))

pinnipeds.data$Month.of.Observation <- factor(pinnipeds.data$Month.of.Observation, 
          levels = c('JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'))

```

```{r sex and all strandings, echo = TRUE}
#Are there any correlations or patterns in age or sex and strandings?

#Sex and all
Sex.all <- pinnipeds.data %>%
  filter(Sex == 'Male' | Sex == 'Female') %>%
  group_by(Sex) %>%
  summarize(cnt = n_distinct(National.Database.Number)) 

Sex.all.yr <- pinnipeds.data %>%
  filter(Sex == 'Male' | Sex == 'Female') %>%
  group_by(Sex, Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number)) 

Sex.all.yr.mo <- pinnipeds.data %>%
  filter(Sex == 'Male' | Sex == 'Female') %>%
  group_by(Sex, Year.of.Observation, Month.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number)) 

##HELP which of these outputs do I use? Mean monthly or mean annual? Monthly averages have smaller stdev, but maybe because differeneces between sex are smaller when not summed to the year level.
#Anova shows annual mean stranding is different between sexes, p < 0.05
summary(aov(cnt ~ Sex, Sex.all.yr))
sd(Sex.all.yr$cnt)

#Anova shows monthly mean stranding is different between sexes, p < 0.05
summary(aov(cnt ~ Sex, Sex.all.yr.mo)) #mean monthly
summary(aov(cnt ~ Sex + Year.of.Observation, Sex.all.yr.mo)) #mean monthly given difs in years?
sd(Sex.all.yr.mo$cnt)

#100% stacked bar chart - year - not much variation across years, though low perc females in 09-10.
Sex.all.yr.figure.stack <- ggplot(Sex.all.yr, 
        aes(x = as.factor(Year.of.Observation), y = cnt, fill = Sex)) +
  geom_bar(stat = 'identity', position = 'fill') +
  scale_y_continuous(labels = comma) +
  xlab("") + ylab("Proportion of Strandings") +
  plot_theme(legend.position = 'top')
ggsave(Sex.all.yr.figure.stack, file = "./Figures/Sex.all.yr.figure.stack.pdf")

Sex.all.yr.figure <- 
  ggplot(Sex.all.yr, aes(x = as.factor(Year.of.Observation), y = cnt, fill = Sex)) +
  geom_bar(stat = 'identity') +
  scale_y_continuous(labels = comma) +
  xlab("") + ylab("Total Strandings") +
  plot_theme(legend.position = 'top')
ggsave(Sex.all.yr.figure, file = "./Figures/Sex.all.yr.figure.pdf")

#Larger IQR for males
Sex.all.yr.boxplot <- 
  ggplot(Sex.all.yr.mo, 
      aes(x = as.factor(Year.of.Observation), y = cnt, fill = Sex)) +
  geom_boxplot() +
  scale_y_continuous(labels = comma) +
  xlab("") + ylab("Mean Monthly Strandings") +
  plot_theme(legend.position = 'top')
ggsave(Sex.all.yr.boxplot, file = "./Figures/Sex.all.yr.boxplot.pdf")

#100% stacked bar chart - month - higher female percentage in august compared to december
Sex.all.month.figure <- 
  ggplot(Sex.all.yr.mo, aes(x = as.factor(Month.of.Observation), y = cnt, fill = Sex)) +
  geom_bar(stat = 'identity', position = 'fill') +
  xlab("") + ylab("Proportion of Strandings") +
  plot_theme(legend.position = 'top')
ggsave(Sex.all.month.figure, file = "./Figures/Sex.all.mo.figure.pdf")

#Anova shows monthly mean stranding is different between sexes, months, but not months for the sexes, p < 0.05
summary(aov(cnt ~ Month.of.Observation*Sex, Sex.all.yr.mo))

#Tukey comparisons show which months males and females are different from each other and different from themselves. 
sexmonthsTukey <- TukeyHSD(aov(cnt ~ Sex + Month.of.Observation + Month.of.Observation*Sex, Sex.all.yr.mo))

# #Would be great to subset for sig p values
sigmonths <- sexmonthsTukey$Sex[4] < 0.01

```


```{r Sex and HI}
#From above, we can see that there are differences between sexes for overall cases, but are these differences also apparent for human interaction cases?

#Sex and HI

Sex.HI <- pinnipeds.data %>%
  filter(Sex == 'Male' | Sex == 'Female') %>%
  group_by(Sex, Findings.of.Human.Interaction) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  dcast(Sex ~ Findings.of.Human.Interaction, value.var = 'cnt') 

Sex.HI.yr <- pinnipeds.data %>%
  filter(Sex == 'Male' | Sex == 'Female') %>%
  filter(Findings.of.Human.Interaction == 'Y' & Interaction.Type != 'NA') %>%
  group_by(Sex, Year.of.Observation, Interaction.Type) %>%
  summarize(cnt = n_distinct(National.Database.Number)) 

#Anova shows interaction types are different, sexes are different, and types for each sex are different. Look below at pairwise for specific differences.
summary(aov(cnt ~ Sex + Interaction.Type + Sex*Interaction.Type, Sex.HI.yr))

#Tukey comparisons show which sex/type combinations are different from each other. I would prefer to just compare Male-Female gunshot wounds, not male gunshots versus female fisheries.
TukeyHSD(aov(cnt ~ Sex*Interaction.Type, Sex.HI.yr))

#100% stacked bar chart - year - females fewer gunshot
HI.type.sex.figure <- ggplot(Sex.HI.yr, aes(x = Interaction.Type, y = cnt, fill = Sex)) +
  geom_bar(stat = 'identity', position = 'fill') +
  xlab("") + ylab("Proportion of Strandings") +
  plot_theme(legend.position = 'top')
ggsave(HI.type.sex.figure, file = "./Figures/HI.type.sex.figure.pdf")

```


```{r age class}
#Do specific age classes strand more or less frequently than others?

age.all <- pinnipeds.data %>%
  group_by(Age.Class) %>%
  summarize(cnt = n_distinct(National.Database.Number)) 
 
age.all$prop <- round(age.all$cnt/sum(age.all$cnt), 2)*100

age.all.table <- age.all
colnames(age.all.table) <- c("Age", "Number", "Proportion (%)")

age.sex.all <- pinnipeds.data %>%
  group_by(Sex, Age.Class) %>%
  summarize(cnt = n_distinct(National.Database.Number)) 

age.sex.all.figure <- 
  ggplot(age.sex.all, aes(x = as.factor(Age.Class), y = cnt, fill = Sex)) +
  geom_bar(stat = 'identity', position = 'fill') +
  xlab("") + ylab("Proportion of Strandings") +
  plot_theme(legend.position = 'top') +
  scale_fill_brewer(palette = 'Set1')
ggsave(age.sex.all.figure, file = "./Figures/age.sex.all.figure.pdf")

age.sex.table <- age.sex.all %>% 
  dcast(Age.Class ~ Sex, value.var = 'cnt') %>% 
  transform(Prop.Fem = round((Female)/(Female + Male + Unid), 2)*100,
            Prop.Male = round(Male/(Female + Male + Unid), 2)*100,
            Prop.Unid = round(Unid/(Female + Male + Unid), 2)*100) %>%
  select(c(Age.Class, Female, Prop.Fem, Male, Prop.Male, Unid, Prop.Unid))
colnames(age.sex.table) <- c("Age", "Female (N)", "Female (%)", "Male (N)", "Male (%)", "Unid. (N)", "Unid. (%)")
average.sex <- c(as.character("Average"), "--", mean(age.sex.table[,3]), "--", mean(age.sex.table[,5]), "--", mean(age.sex.table[,7]))

age.sex.table <- rbind(age.sex.table, average.sex, stringsAsFactors = F)


age.sex.table <- write.csv(age.sex.table, file = "./Figures/age.sex.table.csv", row.names = F)


age.sex.stats <- pinnipeds.data %>%
  group_by(Sex, Year.of.Observation, Age.Class) %>%
  summarize(cnt = n_distinct(National.Database.Number)) 

summary(aov(cnt ~ Sex*Age.Class, data = age.sex.stats))
TukeyHSD(aov(cnt ~ Sex*Age.Class, data = age.sex.stats))

```


```{r all strandings over time}

#Are the number of cases of all combined species increasing or decreasing over time?

data.by.year <- pinnipeds.data %>% 
  group_by(Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number)) 

#Statistically significant change in all stranding cases in OR and WA combined over time (p < 0.05, 25 strandings per year increase).
timeseries.all.model <- glm(cnt ~ Year.of.Observation, family = "poisson", data = data.by.year)

summary(timeseries.all.model)
plot(timeseries.all.model$residuals)
hist(timeseries.all.model$residuals)
plot(abs(timeseries.all.model$residuals) ~ timeseries.all.model$fitted)
qqnorm(timeseries.all.model$residuals)
qqline(timeseries.all.model$residuals)

all.yr.figure <- 
  ggplot(data.by.year, aes(x = Year.of.Observation, y = cnt)) + 
  geom_point(position = "identity") +
  geom_smooth(method = "lm", se = FALSE, col = 'black', linetype = 3) +
  xlab("") + ylab("Annual Strandings") +
  scale_y_continuous(labels = comma) +
  plot_theme() +
  scale_color_brewer(palette = 'Set1') 
ggsave(all.yr.figure, file = "./Figures/all.year.figure.pdf")

```


```{r HI and FI number of cases over time}

#Are the number of HI cases of all combined species increasing or decreasing over time?

HI.by.year <- pinnipeds.data %>%
  filter(Findings.of.Human.Interaction == 'Y') %>%
  group_by(Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number)) 

#Regression shows significant increase (6/yr) of all HI cases, p < 0.05
timeseries.HI.model <- lm(cnt ~ Year.of.Observation, data = HI.by.year)

plot(timeseries.HI.model$residuals)
hist(timeseries.HI.model$residuals)
summary(timeseries.HI.model)

#anova confirms years are different, p-val < 0.05
summary(aov(cnt ~ Year.of.Observation, data = HI.by.year))

HI.year.figure <- 
  ggplot(HI.by.year, aes(x = Year.of.Observation, y = cnt)) + 
  geom_point(position = "identity") +
  geom_smooth(method = "lm", se = FALSE, col = 'black', linetype = 3) +
  xlab("") + ylab("Annual Human Interaction Cases") +
  scale_y_continuous(labels = comma) +
  #scale_x_continuous(breaks = c(1989:2015)) +
  plot_theme(legend.position = 'top') +
  scale_color_brewer(palette = 'Set1')
ggsave(HI.year.figure, file = "./Figures/HI.year.figure.pdf")
```

```{r HI types over time}
#Are specific types of HI cases changing over time?

HI.by.year.type <- pinnipeds.data %>%
  filter(Findings.of.Human.Interaction == 'Y' & Interaction.Type != 'NA') %>%
  group_by(Interaction.Type, Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number)) 

#Regression shows there is an effect of year for all HI types, that they are increasing over time (gunshot by 22/yr).
summary(lm(cnt ~ Year.of.Observation*Interaction.Type, data = HI.by.year.type))

#Tukey shows average annual HI types are not all different from one another
TukeyHSD(aov(cnt ~ Interaction.Type, data = HI.by.year.type))

HI.type.year.figure <- 
  ggplot(HI.by.year.type, aes(x = Year.of.Observation, y = cnt, 
                              group = Interaction.Type, col = Interaction.Type)) + 
  geom_point(position = "identity") +
  geom_smooth(method = "lm", se = FALSE) +
  xlab("") + ylab("Human Interaction Cases") +
  plot_theme(legend.position = 'top') + 
  scale_color_brewer(palette = 'Set1')
ggsave(HI.type.year.figure, file = "./Figures/HI.type.year.figure.pdf")

```

```{r categorical species comparison for all years all HI and FI}

#Do some species strand more frequently than others?  All years combined here, time series in below chunk.

# Yes, harbor seals, CSL, and stellers strand more

species <- pinnipeds.data %>%
  group_by(Pinniped.Common.Name) %>%
  summarize(cnt = n_distinct(National.Database.Number))

species.year <- pinnipeds.data %>%
  filter(Pinniped.Common.Name != 'Unidentified') %>%
  group_by(Year.of.Observation, Pinniped.Common.Name) %>%
  summarize(cnt = n_distinct(National.Database.Number)) 
  
species.year.mean <- pinnipeds.data %>%
  group_by(Year.of.Observation, Pinniped.Common.Name) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  group_by(Pinniped.Common.Name) %>%
  summarize(mean = mean(cnt))

species.figure <- species.year %>%
  filter(Pinniped.Common.Name != 'Unidentified') %>%
  ggplot(aes(Pinniped.Common.Name, cnt)) +
  geom_boxplot() +
  scale_y_continuous(labels = comma) +
  xlab("") + ylab("Annual Strandings") +
  plot_theme()
ggsave(species.figure, file = "./Figures/species.figure.pdf")


#Anova shows average annual strandings are significantly different between species. Should I also have year in the anova?
summary(aov(cnt ~ Pinniped.Common.Name*Year.of.Observation, data = species.year))

#Tukey shows which species are different from each other
#pairwise.t.test(species.year$cnt, species.year$Pinniped.Common.Name, p.adj = "none")
TukeyHSD(aov(cnt ~ Pinniped.Common.Name, data = species.year))

#Are HI and FI cases signficantly different between species as well?
##HI cases
species.year.HI <- pinnipeds.data %>%
  filter(Pinniped.Common.Name != 'Unidentified') %>%
  filter(Findings.of.Human.Interaction == 'Y' & Interaction.Type != 'NA') %>%
  group_by(Year.of.Observation, Pinniped.Common.Name) %>%
  summarize(cnt = n_distinct(National.Database.Number))

species.year.HI.figure <- 
  ggplot(species.year.HI, aes(Pinniped.Common.Name, cnt)) +
  geom_boxplot() +
  xlab("") + ylab("Annual Human Interaction Cases") +
  scale_y_continuous(labels = comma) +
  plot_theme()
ggsave(species.year.HI.figure, file = "./Figures/species.year.HI.figure.pdf")

#Anova shows that yes, the mean annual HI strandings are different across species.
#Harbor seals are different from everything else, but no other sig difs
summary(aov(cnt ~ Pinniped.Common.Name, data = species.year.HI))

TukeyHSD(aov(cnt ~ Pinniped.Common.Name, data = species.year.HI))

##FI cases
##CSLs are shot more than any other species, and way more proportionally than overall strandings or HI
species.year.FI <- pinnipeds.data %>%
  filter(Fishery.Interaction == 'Y' & Pinniped.Common.Name != 'Unidentified') %>%
  group_by(Year.of.Observation, Pinniped.Common.Name) %>%
  summarize(cnt = n_distinct(National.Database.Number))

species.fish.figure <- 
  ggplot(species.year.FI, aes(Pinniped.Common.Name, cnt)) +
  geom_boxplot() +
  xlab("") + ylab("Annual Fisheries Interactions") +
  plot_theme()
ggsave(species.fish.figure, file = "./Figures/species.fish.figure.pdf")

#Sig difs overall, but not pairwise?
summary(aov(cnt ~ Pinniped.Common.Name, data = species.year.FI))
TukeyHSD(aov(cnt ~ Pinniped.Common.Name, data = species.year.FI))

species.year.shot <- pinnipeds.data %>%
  filter(Shot == 'Y' & Pinniped.Common.Name != 'Unidentified') %>%
  group_by(Year.of.Observation, Pinniped.Common.Name) %>%
  summarize(cnt = n_distinct(National.Database.Number))

species.shot.figure <- 
  ggplot(species.year.shot, aes(Pinniped.Common.Name, cnt)) +
  geom_boxplot() +
  xlab("") + ylab("Annual Gunshot Woundss") +
  plot_theme()
ggsave(species.shot.figure, file = "./Figures/species.shot.figure.pdf")

#No sig difs between species for gunshot wound cases. Sig difs for more recent years only. p = 0.06
summary(aov(cnt ~ Pinniped.Common.Name, data = species.year.shot))
TukeyHSD(aov(cnt ~ Pinniped.Common.Name, data = species.year.shot))

```


```{r timeline species comparison for all HI and FI}

#Are strandings or HI FI cases of certain species increasing or decreasing over time?
#We would expect proportions of certain types of cases to remain constant over time, so are the proportions of HI and FI cases changing?

#All species changing over time; HELP output suggests negative slope, but looks like an increasing trend in figure for stellers 
summary(lm(cnt ~ Pinniped.Common.Name + Year.of.Observation, data = species.year))

summary(lm(cnt ~ Pinniped.Common.Name + Year.of.Observation, data = species.year.HI))
    
species.all.figure <- 
  ggplot(species.year, aes(x = Year.of.Observation, y = cnt, 
                group = Pinniped.Common.Name, col = Pinniped.Common.Name)) +
  geom_point(stat = 'identity', position = 'jitter') + 
  geom_smooth(method = 'lm', se = F) +
  ylab("Annual Strandings") + xlab("") + 
  scale_y_continuous(labels = comma) +
  plot_theme(legend.position = 'top', 
             legend.text = element_text(size = 8)) +
  scale_color_brewer(palette = 'Set2')
ggsave(species.all.figure, file = "./Figures/species.all.figure.pdf")

#strandings by year, species stacked
species.all.figure.stacked <- 
  ggplot(species.year, aes(x = factor(Year.of.Observation), y = cnt, fill = Pinniped.Common.Name)) +
  geom_bar(stat = 'identity') + 
  ylab("Annual Strandings") + xlab("") + 
  scale_y_continuous(labels = comma) +
  plot_theme(legend.position = 'top') + 
  scale_fill_brewer(palette = 'Set2')  
ggsave(species.all.figure.stacked, file = "./Figures/species.all.figure.stacked.pdf")

species.HI.figure <- 
  ggplot(species.year.HI, aes(x = factor(Year.of.Observation), y = cnt, 
                col = Pinniped.Common.Name, group = Pinniped.Common.Name)) +
  geom_point(stat = 'identity') + 
  geom_smooth(method = 'lm', se = F) +
  ylab("Human Interaction Cases") + xlab("") + 
  plot_theme(legend.position = 'top', 
             legend.text = element_text(size = 8)) + 
  scale_color_brewer(palette = 'Set1')
ggsave(species.HI.figure, file = "./Figures/species.HI.figure.pdf")

#Are fisheries interactions cases changing over time for particular species? 
# Yes, harbors going up, others going down? But the figure really looks like they're going up. Do I need to have year in the model?

#Anova shows average annual FI cases are different across species
summary(aov(cnt ~ Pinniped.Common.Name, data = species.year.FI))

model.species.FI <- summary(lm(cnt ~ Year.of.Observation + Pinniped.Common.Name, species.year.FI))

plot(model.species.FI$residuals)
hist(model.species.FI$residuals)

species.year.FI.figure <- 
  ggplot(species.year.FI, aes(x = factor(Year.of.Observation), y = cnt, 
            col = Pinniped.Common.Name, group = Pinniped.Common.Name)) +
  geom_point(stat = 'identity', position = 'jitter') + 
  geom_smooth(method = 'lm', se = F) +
  ylab("Fisheries and Gunshot Wounds") + xlab("") + 
  plot_theme(legend.position = 'top', 
             legend.text = element_text(size = 8)) + 
  scale_color_brewer(palette = 'Set1')
ggsave(species.year.FI.figure, file = "./Figures/species.year.FI.figure.pdf")

#Stacked
stacked.FI.figure <- 
  ggplot(species.year.FI, aes(x = factor(Year.of.Observation), y = cnt, 
              fill = Pinniped.Common.Name)) +
  geom_bar(stat = 'identity') + 
  ylab("Total fisheries Interactions") + xlab("") + 
  plot_theme(legend.position = 'top') + 
  scale_fill_brewer(palette = 'Set2') 
ggsave(stacked.FI.figure, file = "./Figures/stacked.FI.figure.pdf")

#Exploring single species 

# year.species.FI.TEST <- pinnipeds.data %>%
#   filter(Pinniped.Common.Name == 'California sea lion') %>%
#   filter(Fishery.Interaction == 'Y') %>%
#   group_by(Year.of.Observation) %>%
#   summarize(cnt = n_distinct(National.Database.Number)) 
# 
# summary(lm(cnt ~ Year.of.Observation, year.species.FI.TEST))


```

```{r proportion of cases}
#Is the proportion of HI cases changing? Above I noted that overall cases are level/decreasing, but if HI is increasing, what does that mean?
#Proportion of HI cases goes up
#Proportion of FI cases doesn't seem to go up as much
#Proportion of shots goes up

year.prop.HI <- pinnipeds.data %>%
  group_by(Findings.of.Human.Interaction, Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  dcast(Year.of.Observation ~ Findings.of.Human.Interaction, value.var = 'cnt') %>%
  transform(Prop.HI = round(Y/(Y + N + CBD), 2)*100)

#test prevalence for year groups?
HI.prev.species.TEST <- pinnipeds.data %>%
  filter(Pinniped.Common.Name != 'Unidentified') %>% 
  transform(Decade = ifelse(Year.of.Observation < 2000, "1", 
                            ifelse(Year.of.Observation > 1999 & Year.of.Observation < 2010, "2", ifelse(Year.of.Observation > 2009, "3", "")))) %>%
  group_by(Pinniped.Common.Name, Decade, Findings.of.Human.Interaction) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  dcast(Pinniped.Common.Name + Decade ~ Findings.of.Human.Interaction, value.var = 'cnt')
HI.prev.species.TEST[is.na(HI.prev.species.TEST)] <- 0
HI.prev.species.TEST <- HI.prev.species.TEST %>%
    transform(Prop.HI = round(Y/(Y+N+CBD), 2))

ggplot(HI.prev.species.TEST, aes(Decade, Prop.HI, col = Pinniped.Common.Name)) +
  geom_point(stat = 'identity') + 
  geom_line() +
  geom_smooth(method = 'lm', se = F) +
  pubfigure_theme(legend.position = 'top')

#proportion of HI per species - prevalence
HI.prev.species.table <- pinnipeds.data %>%
  filter(Pinniped.Common.Name != 'Unidentified') %>% 
  group_by(Pinniped.Common.Name, Year.of.Observation, Findings.of.Human.Interaction) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  dcast(Pinniped.Common.Name + Year.of.Observation ~ Findings.of.Human.Interaction, value.var = 'cnt')
HI.prev.species.table[is.na(HI.prev.species.table)] <- 0
HI.prev.species.table <- HI.prev.species.table %>%
    transform(Prop.HI = round(Y/(Y+N+CBD), 2))

ggplot(HI.prev.species.table, aes(Year.of.Observation, Prop.HI, col = Pinniped.Common.Name)) +
  geom_point(stat = 'identity') + 
  geom_line() +
  #geom_smooth(method = 'lm', se = F) +
  pubfigure_theme(legend.position = 'top')

#Need stats for proportions over time - can I do regression on a proportion?
summary(lm(Prop.HI ~ Year.of.Observation + Pinniped.Common.Name, data = HI.prev.species.table))

#Prevalence of all combined species
HI.prev <- pinnipeds.data %>%
  group_by(Year.of.Observation, Findings.of.Human.Interaction) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  dcast(Year.of.Observation ~ Findings.of.Human.Interaction, value.var = 'cnt')
HI.prev[is.na(HI.prev)] <- 0
HI.prev <- HI.prev %>%
    transform(Prop.HI = round(Y/(Y+N+CBD), 2))

ggplot(HI.prev, aes(Year.of.Observation, Prop.HI)) +
  geom_point(stat = 'identity') + 
  geom_line() +
  geom_smooth(method = 'lm', se = F, col = "black", linetype = 3) +
  xlab("") + ylab("Prevalence of Human Interactions") +
  pubfigure_theme(legend.position = 'top')

#Need stats for proportions over time - can I do regression on a proportion?
summary(lm(Prop.HI ~ Year.of.Observation, data = HI.prev))

#Prevalence of specific HI types per species over time in chunk near bottom - "allprev"


#Proportion of fisheries
year.prop.FI <- pinnipeds.data %>%
  group_by(Fishery.Interaction, Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  dcast(Year.of.Observation ~ Fishery.Interaction, value.var = 'cnt') %>%
  transform(Prop.FI = round(Y/(Y + N), 2))

year.prop.shot <- pinnipeds.data %>%
  group_by(Shot, Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  dcast(Year.of.Observation ~ Shot, value.var = 'cnt') %>%
  transform(Prop.shot = round(Y/(Y + N), 2))

year.prop.FI.shot <- pinnipeds.data %>%
  group_by(Shot, Fishery.Interaction, Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  transform(Fishery.Shot = 
              ifelse(Fishery.Interaction == 'Y', "Y", 
                     ifelse(Shot == 'Y', "Y", "N"))) %>%
  group_by(Fishery.Shot, Year.of.Observation) %>%
  summarize(sum = sum(cnt)) %>%
  dcast(Year.of.Observation ~ Fishery.Shot, value.var = 'sum') %>%
  transform(Prop.FI.shot = round(Y/(Y + N), 2))
```

```{r monthly all HI FI}

#Are there seasonal patterns in all stranding cases? Only alive and fresh dead because timing matters - hard to tell when decomposed individuals stranded
monthly.all <- pinnipeds.data %>%
  filter(Observation.Status == 'ALIVE' | Observation.Status == 'FRESH DEAD') %>%
  group_by(Year.of.Observation, Month.of.Observation, Sex, Age.Class) %>%
  summarize(cnt = n_distinct(National.Database.Number))

monthly.stats <- monthly.all %>%
  group_by(Year.of.Observation, Month.of.Observation) %>%
  summarize(cnt = sum(cnt))

#Overall anova and pairwise tests show that there is a seasonal peak (ie some months are different than others)
summary(aov(cnt ~ Month.of.Observation, data = monthly.stats))
TukeyHSD(aov(cnt ~ Month.of.Observation, data = monthly.stats))
#pairwise.t.test(monthly.all$cnt, monthly.all$Month.of.Observation, p.adj = "none")

#All monthly cases by sex
monthly.sex.figure <- 
  monthly.all %>% group_by(Month.of.Observation, Sex) %>%
  summarize(sum = sum(cnt)) %>%
ggplot(aes(x = factor(Month.of.Observation), y = sum, fill = Sex)) +
  geom_bar(stat = 'identity') +
  ylab("Total Strandings") + xlab("") + 
  scale_y_continuous(labels = comma) +
  plot_theme(legend.position = 'top') + 
  scale_fill_brewer(palette = 'Set1')
ggsave(monthly.sex.figure, file = "./Figures/monthly.sex.figure.pdf")

#Monthly strandings by age class
monthly.age.figure <- monthly.all %>% 
  group_by(Month.of.Observation, Age.Class) %>%
  summarize(sum = sum(cnt)) %>%
  ggplot(aes(x = factor(Month.of.Observation), y = sum, fill = as.factor(Age.Class))) +
  geom_bar(stat = 'identity') +
  ylab("Total Strandings") + xlab("") + 
  scale_y_continuous(labels = comma) +
  plot_theme(legend.position = 'top', 
             legend.text = element_text(size = 8)) + 
  scale_fill_brewer(palette = 'Set3')
ggsave(monthly.age.figure, file = "./Figures/monthly.age.figure.pdf")

monthly.age.stats <- monthly.all %>% 
  group_by(Month.of.Observation, Year.of.Observation, Age.Class) %>%
  summarize(cnt = sum(cnt))

TukeyHSD(aov(cnt ~ Month.of.Observation + Age.Class, data = monthly.age.stats))

##Stats for age HI type
age.HI.stats <- pinnipeds.data %>%
  filter(Findings.of.Human.Interaction == 'Y' & 
           Interaction.Type != 'NA' & Age.Class != 'Unid') %>%
  group_by(Age.Class, Year.of.Observation, Interaction.Type) %>%
  summarize(cnt = n_distinct(National.Database.Number)) 

summary(aov(cnt ~ Age.Class + Interaction.Type, data = age.HI.stats))
TukeyHSD(aov(cnt ~ Age.Class + Interaction.Type + Age.Class*Interaction.Type, data = age.HI.stats))

#Seasonal age composition - pups are the only one that has the seasonal peak
monthly.age <- pinnipeds.data %>% group_by(Month.of.Observation, Age.Class) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  dcast(Month.of.Observation ~ Age.Class, value.var = 'cnt') %>%
  transform(Tot = Pup + Yearling + Subadult + Adult + Unid) %>%
  transform(Pup.prop = round(Pup/Tot, 2)*100)

monthly.age.HI <- pinnipeds.data %>%
  filter(Findings.of.Human.Interaction == 'Y' & Interaction.Type != 'NA') %>%
  group_by(Month.of.Observation, Age.Class) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  dcast(Month.of.Observation ~ Age.Class, value.var = 'cnt') %>%
  transform(Tot = Pup + Yearling + Subadult + Adult + Unid) %>%
  transform(Pup.prop = round(Pup/Tot, 2)*100)

#Peaks by the years
monthly.years.figure <- 
  ggplot(monthly.all, aes(x = factor(Month.of.Observation), y = cnt, 
        group = factor(Year.of.Observation), color = factor(Year.of.Observation))) +
  #geom_area() +
  geom_line(aes(group = factor(Year.of.Observation))) + 
  #geom_smooth(se = F) +
  ylab("Strandings per Month") + xlab("") + 
  scale_y_continuous(labels = comma) +
  plot_theme() #+ 
  #scale_color_brewer()
ggsave(monthly.years.figure, file = "./Figures/monthly.years.figure.pdf")

#Are there seasonal patterns in HI cases?

monthly.HI <- pinnipeds.data %>%
  filter(Findings.of.Human.Interaction == 'Y') %>%
  filter(Observation.Status == 'ALIVE' | Observation.Status == 'FRESH DEAD') %>%
  group_by(Month.of.Observation, Year.of.Observation, Interaction.Type, Sex, Age.Class) %>%
  summarize(cnt = n_distinct(National.Database.Number))

monthly.HI.yr.mo <- pinnipeds.data %>%
  filter(Findings.of.Human.Interaction == 'Y') %>%
  filter(Observation.Status == 'ALIVE' | Observation.Status == 'FRESH DEAD') %>%
  group_by(Month.of.Observation, Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number))

#Regression shows different in Jan and summer
summary(lm(cnt ~ Month.of.Observation, data = monthly.HI.yr.mo))

summary(aov(cnt ~ Month.of.Observation, data = monthly.HI.yr.mo))

monthly.HI.YNCBD <- pinnipeds.data %>% 
  filter(Observation.Status == 'ALIVE' | Observation.Status == 'FRESH DEAD') %>%
  group_by(Findings.of.Human.Interaction, Month.of.Observation) %>% 
  summarize(cnt = n_distinct(National.Database.Number)) 

monthly.HI.YNCBD.prop <- pinnipeds.data %>% 
  filter(Observation.Status == 'ALIVE' | Observation.Status == 'FRESH DEAD') %>%
  group_by(Findings.of.Human.Interaction, Month.of.Observation) %>% 
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  dcast(Month.of.Observation ~ Findings.of.Human.Interaction, value.var = 'cnt') %>%
  transform(prop.Y = round(Y/(CBD+N+Y), 2)*100)

#Bar chart showing proportion of Y, N, and CBD HI cases
ggplot(monthly.HI.YNCBD, aes(x = factor(Month.of.Observation), y = cnt, fill = Findings.of.Human.Interaction)) +
  geom_bar(stat = 'identity') + 
  ylab("Total Human Interaction Cases") + xlab("") + 
  plot_theme(legend.position = 'top') + 
  scale_fill_brewer(palette = 'Set1') 

#Bar chart showing only HI cases - sum of total ever cases in each month
monthly.HI.figure <- monthly.HI %>%
  group_by(Month.of.Observation) %>%
  summarize(cnt = sum(cnt)) %>%
  ggplot(aes(x = factor(Month.of.Observation), y = cnt)) +
  geom_bar(stat = 'identity') +
  ylab("Total Human Interaction Cases") + xlab("") +
  scale_y_continuous(labels = comma) +
  plot_theme() + 
  scale_fill_brewer(palette = 'Set1')
ggsave(monthly.HI.figure, file = "./Figures/monthly.HI.figure.pdf")

#Bar chart showing monthly strandings by interaction type
monthly.HI.figure.stacked <- monthly.HI %>% 
  filter(Interaction.Type != 'NA') %>%
  group_by(Month.of.Observation, Interaction.Type) %>%
  summarize(sum = sum(cnt)) %>%
  ggplot(aes(x = factor(Month.of.Observation), y = sum, fill = Interaction.Type)) +
  geom_bar(stat = 'identity') +
  ylab("Total Human Interaction Cases") + xlab("") + 
  plot_theme(legend.position = 'top') + 
  scale_fill_brewer(palette = 'Set1')
ggsave(monthly.HI.figure.stacked, file = "./Figures/monthly.HI.figure.stacked.pdf")

#Bar chart showing monthly strandings by sex
monthly.HI %>% group_by(Month.of.Observation, Sex) %>%
  summarize(sum = sum(cnt)) %>%
ggplot(aes(x = factor(Month.of.Observation), y = sum, fill = Sex)) +
  geom_bar(stat = 'identity') +
  ylab("Total Human Interaction Cases") + xlab("") + 
  plot_theme(legend.position = 'top') + 
  scale_fill_brewer(palette = 'Set1')

#Monthly HI strandings by age class
monthly.HI.age.figure <- 
  monthly.HI %>% group_by(Month.of.Observation, Age.Class) %>%
  summarize(sum = sum(cnt)) %>%
ggplot(aes(x = factor(Month.of.Observation), y = sum, fill = Age.Class)) +
  geom_bar(stat = 'identity') +
  ylab("Total Human Interaction Cases") + xlab("") + 
  plot_theme(legend.position = 'top') + 
  scale_fill_brewer(palette = 'Set1')
ggsave(monthly.HI.age.figure, file = "./Figures/monthly.HI.age.figure.pdf")

#Peaks by the years
monthly.HI.year.figure <- 
  ggplot(monthly.HI, aes(x = factor(Month.of.Observation), y = cnt, group = factor(Year.of.Observation), color = factor(Year.of.Observation))) +
  #geom_line(aes(group = factor(Year.of.Observation))) + 
  geom_smooth(se = F) +
  ylab("Monthly Human Interaction Cases") + xlab("") + 
  plot_theme() #+ 
  #scale_color_brewer(palette = 'Set3')
ggsave(monthly.HI.year.figure, file = "./Figures/monthly.HI.year.figure.pdf")

#Is there an effect of month on FI?
monthly.FI <- pinnipeds.data %>%
  filter(Fishery.Interaction == 'Y') %>%
  filter(Observation.Status == 'ALIVE' | Observation.Status == 'FRESH DEAD') %>%
  group_by(Year.of.Observation, Month.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number))

#HELP - in theory, can I do regressions on month? Now I'm not sure what that really means.... Regression output shows some months dif than others
summary(lm(cnt ~ Month.of.Observation, data = monthly.FI))

summary(aov(cnt ~ Month.of.Observation, data = monthly.FI))

#Peaks by the years
monthly.FI.year.figure <- 
  ggplot(monthly.FI, aes(x = factor(Month.of.Observation), y = cnt, 
              group = factor(Year.of.Observation), color = factor(Year.of.Observation))) +
  geom_line(aes(group = factor(Year.of.Observation))) + 
  geom_smooth(se = F) +
  ylab("Monthly Fisheries Interactions") + xlab("") + 
  plot_theme() #+ 
 # scale_color_brewer(palette = 'Set3')
ggsave(monthly.FI.year.figure, file = "./Figures/monthly.FI.year.figure.pdf")
```

```{r monthly by species}
#Monthly per species
#HELP: should this be done per species per month per year, so it is monthly FI cases in a given year (here)? Or just per species all years combined each month, so it is summed across years (as above in HI and all cases per species)? 

monthly.species <- pinnipeds.data %>%
  filter(Observation.Status == 'ALIVE' | Observation.Status == 'FRESH DEAD') %>%
  filter(Pinniped.Common.Name != 'Unidentified') %>%
  group_by(Month.of.Observation, Pinniped.Common.Name, Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number))

#Help - Harbor seals only one really showing seasonal peak, maybe small small for ES and SSL, later for CSL. How do I answer the question: which species show seasonal peak? 
#Regression shows different from each other, but we already know that from the above. I think I got the summer harbors peak here: 
summary(lm(cnt ~ Month.of.Observation*Pinniped.Common.Name, data = monthly.species))

#summary(aov(cnt ~ Month.of.Observation*Pinniped.Common.Name, data = monthly.species))

monthly.species.figure <- 
  pinnipeds.data %>%
  filter(Observation.Status == 'ALIVE' | Observation.Status == 'FRESH DEAD') %>%
  filter(Pinniped.Common.Name != 'Unidentified') %>%
  group_by(Month.of.Observation, Pinniped.Common.Name) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  ggplot(aes(x = factor(Month.of.Observation), y = cnt, 
          group = Pinniped.Common.Name, color = Pinniped.Common.Name)) +
  #geom_line(aes(group = Pinniped.Common.Name)) + 
  geom_smooth(se = F) +
  ylab("Total Monthly Strandings") + xlab("") + 
  plot_theme(legend.position = 'top', legend.text = element_text(size = 4)) + 
  scale_color_brewer(palette = 'Set3')
ggsave(monthly.species.figure, file = "./Figures/monthly.species.figure.pdf")

#HI by month per each species
#HELP COMPARE: should this be done per species per month per year, so it is monthly FI cases in a given year (here)? Or just per species per all time series months combined, so it is summed across years (as above in HI and all cases per species)?

monthly.species.HI <- pinnipeds.data %>%
  filter(Observation.Status == 'ALIVE' | Observation.Status == 'FRESH DEAD') %>%
  filter(Findings.of.Human.Interaction == 'Y') %>%
  group_by(Month.of.Observation, Pinniped.Common.Name, Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number)) 

#Help - This is confusing - seems like it matters which species comes first?! Where are CSLs?
summary(lm(cnt ~ Month.of.Observation*Pinniped.Common.Name, data = monthly.species.HI))

summary(aov(cnt ~ Month.of.Observation + Pinniped.Common.Name, data = monthly.species.HI))

monthly.species.HI.figure <- 
  pinnipeds.data %>%
  filter(Observation.Status == 'ALIVE' | Observation.Status == 'FRESH DEAD') %>%
  filter(Findings.of.Human.Interaction == 'Y') %>%
  group_by(Month.of.Observation, Pinniped.Common.Name) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  ggplot(aes(x = factor(Month.of.Observation), y = cnt, group = Pinniped.Common.Name, color = Pinniped.Common.Name)) +
  #geom_line(aes(group = Pinniped.Common.Name)) + 
  geom_smooth(se = F) +
  ylab("Total Monthly Human Interaction Cases") + xlab("") + 
  plot_theme(legend.position = 'top') + 
  scale_color_brewer(palette = 'Set3')
ggsave(monthly.species.HI.figure, file = "./Figures/monthly.species.HI.figure.pdf")

#Human interactions monthly each year

monthly.HI.year <- pinnipeds.data %>% 
  filter(Findings.of.Human.Interaction == 'Y') %>%
  group_by(Month.of.Observation, Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number)) 

monthly.HI.year.figure <- 
  ggplot(monthly.HI.year, 
       aes(x = factor(Month.of.Observation), y = cnt, 
           group = factor(Year.of.Observation), 
           color = factor(Year.of.Observation))) +
  #geom_line(aes(group = factor(Year.of.Observation))) + 
  geom_smooth(se = F) +
  ylab("Monthly Human Interaction Cases") + xlab("") + 
  plot_theme() + 
  scale_color_brewer(palette = 'Set3')
ggsave(monthly.HI.year.figure, file = "./Figures/monthly.HI.year.figure.pdf")

#Monthly species FI

#FI by month per each species
#HELP COMPARE: should this be done per species per month per year, so it is monthly FI cases in a given year (here)? Or just per species per all time series months combined, so it is summed across years (as above in HI and all cases per species)?
 
monthly.species.FI.shot <- pinnipeds.data %>%
  filter(Fishery.Interaction == 'Y' | Shot == 'Y') %>%
  group_by(Month.of.Observation, Pinniped.Common.Name, Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number))

#Again, uncertain how to answer the question of whether some species are experiencing a seasonal peak while others are not
summary(lm(cnt ~ Month.of.Observation + Pinniped.Common.Name, data = monthly.species.FI.shot))

summary(aov(cnt ~ Month.of.Observation*Pinniped.Common.Name, data = monthly.species.FI.shot))

#Better if this is summed across years?
monthly.FI.shot.year.figure <- monthly.species.FI.shot %>%
  group_by(Pinniped.Common.Name, Month.of.Observation) %>%
  summarize(cnt = sum(cnt)) %>%
  ggplot(aes(x = factor(Month.of.Observation), y = cnt, 
          group = Pinniped.Common.Name, color = Pinniped.Common.Name)) +
  #geom_line(aes(group = Pinniped.Common.Name)) + 
  geom_smooth(se = F) +
  ylab("Total Strandings") + xlab("") + 
  plot_theme(legend.position = 'top') + 
  scale_color_brewer(palette = 'Set3')
ggsave(monthly.FI.shot.year.figure, file = "./Figures/monthly.FI.shot.year.figure.pdf")

```

```{r spatial state}
#All by state
year.month.state <- pinnipeds.data %>%
  group_by(State, Year.of.Observation, Month.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number))

year.state.boxplot <- 
  ggplot(year.month.state, aes(x = as.factor(Year.of.Observation), y = cnt, fill = State)) +
  geom_boxplot() +
  xlab("") + ylab("Monthly Strandings") +
  plot_theme(legend.position = 'top') +
  scale_fill_brewer(palette = 'Set1')
ggsave(year.state.boxplot, file = "./Figures/year.state.boxplot.pdf")

year.state.prop <- pinnipeds.data %>%
  group_by(State, Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  dcast(Year.of.Observation ~ State, value.var = 'cnt') %>%
  transform(prop.or = round(OR/(OR+WA), 2)*100)
  
mean(year.state.prop$prop.or)
sum(year.state.prop$OR)/sum(year.month.state$cnt)

#When accounting for differences across years, states are different
summary(lm(cnt ~ Year.of.Observation + State, year.month.state))

#Tukey - average annual strandings in states are significantly different from each other
summary(aov(cnt ~ Year.of.Observation + State, data = year.month.state))

#Bar chart of strandings by state shows slightly more in WA, but similar trends through time. Higher in OR in 2015 and higher in WA in 2010.
all.state.figure <- pinnipeds.data %>% 
  group_by(State, Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
ggplot(aes(x = factor(Year.of.Observation), y = cnt, fill = State)) +
  geom_bar(stat = 'identity', position = position_dodge(width = 0.8), width = 0.6) + 
   ylab("Total Annual Strandings") + xlab("") + 
   plot_theme() + 
   scale_fill_brewer(palette = 'Set1') 
ggsave(all.state.figure, file = "./Figures/all.state.figure.pdf")

#HI by state
HI.year.state <- pinnipeds.data %>%
  filter(Findings.of.Human.Interaction == 'Y' & Interaction.Type != 'NA') %>%
  group_by(State, Year.of.Observation, Interaction.Type) %>%
  summarize(cnt = n_distinct(National.Database.Number))

HI.state.prop <- HI.year.state %>%
  group_by(State, Interaction.Type) %>%
  summarize(cnt = sum(cnt)) %>%
  dcast(Interaction.Type ~ State, value.var = 'cnt') %>%
  transform(prop.or = round(OR/(OR+WA), 2)*100)
  
mean(HI.state.prop$prop.or)
sum(HI.state.prop$OR)/sum(HI.year.state$cnt)

#When accounting for differences across years, states are different
summary(lm(cnt ~ Year.of.Observation + State, HI.year.state))

#Tukey - average annual strandings in states are significantly different from each other
summary(aov(cnt ~ Year.of.Observation + State, data = HI.year.state))

#Bar chart of HI strandings by state shows growing number in OR
HI.state.year.figure <- pinnipeds.data %>% 
  filter(Findings.of.Human.Interaction == 'Y' & Interaction.Type != 'NA') %>%
  group_by(State, Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
    
ggplot(aes(x = factor(Year.of.Observation), y = cnt, fill = State)) +
  geom_bar(stat = 'identity', position = position_dodge(width = 0.8), width = 0.6) + 
   ylab("Annual Human Interaction Cases") + xlab("") + 
   plot_theme() + 
   scale_fill_brewer(palette = 'Set1') 
ggsave(HI.state.year.figure, file = "./Figures/HI.state.year.figure.pdf")

#Species by state

state.species <- pinnipeds.data %>%
  filter(Pinniped.Common.Name != 'Unidentified') %>%
  group_by(Pinniped.Common.Name, State) %>%
  summarize(cnt = n_distinct(National.Database.Number)) 

#Bar chart
state.species.prop.figure <- 
  ggplot(state.species, aes(Pinniped.Common.Name, cnt, fill = State)) + 
  geom_bar(stat = 'identity', position = position_dodge(width = 0.8), width = 0.6) +
  xlab("") + ylab("Total Strandings") +
  scale_y_continuous(labels = comma) +
  plot_theme() + 
   scale_fill_brewer(palette = 'Set1')
ggsave(state.species.prop.figure, file = "./Figures/state.species.prop.figure.pdf")

#100% stacked
state.species.prop.figure <- 
  ggplot(state.species, aes(Pinniped.Common.Name, cnt, fill = State)) + 
  geom_bar(stat = 'identity', position = 'fill') +
  xlab("") + ylab("Proportion of Strandings") +
  plot_theme() + 
   scale_fill_brewer(palette = 'Set1')
ggsave(state.species.prop.figure, file = "./Figures/state.species.prop.figure.pdf")

```

```{r WA counties}
#all strandings by county - WA

allWA.bycounty <- pinnipeds.data %>% 
  filter(County != 'NA' & County != 'Unknown' & State == 'WA') %>% 
  group_by(County, Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number)) 

allWA.bycounty.figure <- ggplot(allWA.bycounty, aes(x = County, y = cnt)) + 
  geom_bar(stat = 'identity')  + 
  ylab("Total Strandings") + xlab("") + 
  scale_y_continuous(labels = comma) +
  plot_theme() + 
  scale_fill_brewer(palette = 'Set1')
ggsave(allWA.bycounty.figure, file = "./Figures/allWA.bycounty.figure.pdf")

#Some counties have higher/lower strandings compared to others
summary(aov(cnt ~ County, allWA.bycounty))

#Increasing in Pierce, San Juan, Grays Harbor, decreasing in Clark, Mason, Skagit?
WAcounty.model <- lm(cnt ~ County + Year.of.Observation, allWA.bycounty)

summary(WAcounty.model)
plot(WAcounty.model$residuals)
hist(WAcounty.model$residuals)
plot(abs(WAcounty.model$residuals) ~ WAcounty.model$fitted)
qqnorm(WAcounty.model$residuals)
qqline(WAcounty.model$residuals)


#all HI by county - WA

WAHI.bycounty <- pinnipeds.data %>% 
  filter(County != 'NA' & State == 'WA' & 
           Findings.of.Human.Interaction == 'Y' & 
           Interaction.Type != 'NA') %>% 
  group_by(County, Interaction.Type, Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number))

#Interaction types different overall
summary(aov(cnt ~ County + Interaction.Type + Year.of.Observation, WAHI.bycounty))

summary(lm(cnt ~ County + Year.of.Observation, WAHI.bycounty))
#Interaction types in each county - Help - same as below - am I getting this right? Shows "other" is increasing in Pierce
summary(lm(cnt ~ County*Interaction.Type + Year.of.Observation, WAHI.bycounty))

#HELPPPPPPP - Need to show that certain counties are disproportionally represented compared to overall strandings
#objects copied from below
bigtable.WA.stats <- pinnipeds.data %>% 
  filter(County != 'NA' & State == 'WA' & County != 'Unknown') %>% 
  group_by(County) %>%
  summarize(all.cnt = n_distinct(National.Database.Number)) %>%
  transform(all.prop = round(all.cnt/sum(all.cnt), 2)*100)

bigtable.WA.HI.stats <- pinnipeds.data %>% 
  filter(County != 'NA' & State == 'WA' & County != 'Unknown' & 
           Findings.of.Human.Interaction == 'Y' & 
           Interaction.Type != 'NA') %>% 
  group_by(County) %>%
  summarize(HI.cnt = n_distinct(National.Database.Number)) %>%
  transform(HI.prop = round(HI.cnt/sum(HI.cnt), 2)*100) %>%
  merge(bigtable.WA.stats, by = 'County')

#Not quite right - shows which proportions are different from each other
pairwise.prop.test(bigtable.WA.HI.stats$HI.cnt, bigtable.WA.HI.stats$all.cnt)
#Not quite right either - shows that proportions are different from each other, not different from the county-level distribution of all strandings
prop.test(bigtable.WA.HI.stats$HI.cnt, bigtable.WA.HI.stats$all.cnt)

#So I think I need to test the proportions, because that would assume n is the baseline?
bigtable.WA.props <- pinnipeds.data %>% 
  filter(County != 'NA' & State == 'WA' & County != 'Unknown') %>% 
  group_by(County) %>%
  summarize(all.cnt = n_distinct(National.Database.Number)) %>%
  transform(all.prop = all.cnt/sum(all.cnt))

bigtable.WA.HI.props <- pinnipeds.data %>% 
  filter(County != 'NA' & State == 'WA' & County != 'Unknown' & 
           Findings.of.Human.Interaction == 'Y' & 
           Interaction.Type != 'NA') %>% 
  group_by(County) %>%
  summarize(HI.cnt = n_distinct(National.Database.Number)) %>%
  transform(HI.prop = HI.cnt/sum(HI.cnt)) %>%
  merge(bigtable.WA.props, by = 'County') %>%
  select(County, all.prop, HI.prop)

smokers  <- c( 83, 90, 129, 70 )
patients <- c( 86, 93, 136, 82 )
pairwise.prop.test(smokers, patients)
prop.test(smokers, patients)

####
WAHI.bycounty.figure <- 
  ggplot(WAHI.bycounty, aes(x = County, y = cnt, fill = Interaction.Type)) + 
  geom_bar(stat = 'identity')  + 
  ylab("Total Human Interaction Cases") + xlab("") + 
  scale_y_continuous(labels = comma) +
  plot_theme(legend.position = 'top') + 
  scale_fill_brewer(palette = 'Set1') 
ggsave(WAHI.bycounty.figure, file = "./Figures/WAHI.bycounty.figure.pdf")


```

```{r OR counties}

#all strandings by county - OR

OR.bycountyallsplit <- pinnipeds.data %>%
  filter(County != 'NA' & County != 'Unknown' & State == 'OR') %>% 
  group_by(County, Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number))
  
allOR.bycounty <- pinnipeds.data %>% 
  filter(County != 'NA' & County != 'Unknown' & State == 'OR') %>% 
  group_by(County, Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number))

#Significant differences across counties
summary(aov(cnt ~ County, allOR.bycounty))
TukeyHSD(aov(cnt ~ County, allOR.bycounty))

#Increasing in Clatsop, Coos, and Lincoln, Curry, Tillamook, Clackamas
ORcounty.model <- lm(cnt ~ County + Year.of.Observation, allOR.bycounty)
summary(ORcounty.model)
plot(ORcounty.model$residuals)
hist(ORcounty.model$residuals)
plot(abs(ORcounty.model$residuals) ~ ORcounty.model$fitted)
qqnorm(ORcounty.model$residuals)
qqline(ORcounty.model$residuals)

allOR.bycounty.figure <- 
  ggplot(allOR.bycounty, aes(x = County, y = cnt)) + 
  geom_bar(stat = 'identity')  + 
  ylab("Total Strandings") + xlab("") + 
  scale_y_continuous(labels = comma) +
  plot_theme() + 
  scale_fill_brewer(palette = 'Set1')
ggsave(allOR.bycounty.figure, file = "./Figures/allOR.bycounty.figure.pdf")


#all HI by county - OR

ORHI.bycounty <- pinnipeds.data %>% 
  filter(County != 'NA' & State == 'OR' & 
           Findings.of.Human.Interaction == 'Y' & 
           Interaction.Type != 'NA') %>% 
  group_by(County, Interaction.Type, Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number)) 

###Overall HI
#Significant differences across counties
summary(aov(cnt ~ County, ORHI.bycounty))
TukeyHSD(aov(cnt ~ County, ORHI.bycounty))

#Increasing just in Clallam, not changing either way anywhere else
summary(lm(cnt ~ County + Year.of.Observation, ORHI.bycounty))

###Specific HI types in specific counties changing over time - help - did I get this regression right? Looks like gunshot wounds are increasing in Clatsop

summary(lm(cnt ~ County*Interaction.Type + Year.of.Observation, ORHI.bycounty))


ORHI.bycounty.figure <- 
  ggplot(ORHI.bycounty, aes(x = County, y = cnt, fill = Interaction.Type)) + 
  geom_bar(stat = 'identity')  + 
  ylab("Human Interaction Cases") + xlab("") + 
  plot_theme(legend.position = 'top') + 
  scale_fill_brewer(palette = 'Set1')
ggsave(ORHI.bycounty.figure, file = "./Figures/ORHI.bycounty.figure.pdf")


```

```{r big counties tables}

#Washington
bigtable.WA <- pinnipeds.data %>% 
  filter(County != 'NA' & State == 'WA' & County != 'Unknown') %>% 
  group_by(County) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  transform(all.prop = round(cnt/sum(cnt), 2)*100)

bigtable.WA.HI <- pinnipeds.data %>% 
  filter(County != 'NA' & State == 'WA' & County != 'Unknown' & 
           Findings.of.Human.Interaction == 'Y' & 
           Interaction.Type != 'NA') %>% 
  group_by(County) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  transform(HI.prop = round(cnt/sum(cnt), 2)*100) %>%
  merge(bigtable.WA, by = 'County')

bigtable.WA.HI.type <- pinnipeds.data %>% 
  filter(County != 'NA' & State == 'WA' & County != 'Unknown' &
           Findings.of.Human.Interaction == 'Y' & 
           Interaction.Type != 'NA') %>% 
  group_by(County, Interaction.Type) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  dcast(County ~ Interaction.Type, value.var = 'cnt') 

bigtable.WA.HI.type[is.na(bigtable.WA.HI.type)] <- 0

bigtable.WA.HI.table <- bigtable.WA.HI.type %>%
  transform(Prop.boat = round(Boat/(Boat + Fisheries + Gunshot + Other)*100),
            Prop.fish = round(Fisheries/(Boat + Fisheries + Gunshot + Other)*100),
            Prop.shot = round(Gunshot/(Boat + Fisheries + Gunshot + Other)*100),
            Prop.other = round(Other/(Boat + Fisheries + Gunshot + Other)*100)) %>%
  select(County, Prop.boat, Prop.fish, Prop.shot, Prop.other) %>%
  merge(bigtable.WA.HI, by = 'County') %>%
  select(County, all.prop, HI.prop, Prop.fish, Prop.shot, Prop.boat, Prop.other)
colnames(bigtable.WA.HI.table) <- c("County", "All Strandings (%)", "Human Interactions (%)", "Fisheries (%)", "Gunshot (%)", "Boat (%)", "Other (%)")

WAcounties.table <- write.csv(bigtable.WA.HI.table, file = "./Figures/WAcounties.table.csv", row.names = F)


#OR
bigtable.OR <- pinnipeds.data %>% 
  filter(County != 'NA' & State == 'OR' & County != 'Unknown') %>% 
  group_by(County) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  transform(all.prop = round(cnt/sum(cnt), 2)*100)

bigtable.OR.HI <- pinnipeds.data %>% 
  filter(County != 'NA' & State == 'OR' & County != 'Unknown' &
           Findings.of.Human.Interaction == 'Y' & 
           Interaction.Type != 'NA') %>% 
  group_by(County) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  transform(HI.prop = round(cnt/sum(cnt), 2)*100) %>%
  merge(bigtable.OR, by = 'County')

bigtable.OR.HI.type <- pinnipeds.data %>% 
  filter(County != 'NA' & State == 'OR' & County != 'Unknown' &
           Findings.of.Human.Interaction == 'Y' & 
           Interaction.Type != 'NA') %>% 
  group_by(County, Interaction.Type) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  dcast(County ~ Interaction.Type, value.var = 'cnt') 

bigtable.OR.HI.type[is.na(bigtable.OR.HI.type)] <- 0

bigtable.OR.HI.table <- bigtable.OR.HI.type %>%
  transform(Prop.boat = round(Boat/(Boat + Fisheries + Gunshot + Other)*100),
            Prop.fish = round(Fisheries/(Boat + Fisheries + Gunshot + Other)*100),
            Prop.shot = round(Gunshot/(Boat + Fisheries + Gunshot + Other)*100),
            Prop.other = round(Other/(Boat + Fisheries + Gunshot + Other)*100)) %>%
  select(County, Prop.boat, Prop.fish, Prop.shot, Prop.other) %>%
  merge(bigtable.OR.HI, by = 'County') %>%
  select(County, all.prop, HI.prop, Prop.fish, Prop.shot, Prop.boat, Prop.other)
colnames(bigtable.OR.HI.table) <- c("County", "All Strandings (%)", "Human Interactions (%)", "Fisheries (%)", "Gunshot (%)", "Boat (%)", "Other (%)")

ORcounties.table <- write.csv(bigtable.OR.HI.table, file = "./Figures/ORcounties.table.csv", row.names = F)
```

```{r weight length, eval = FALSE, echo = FALSE}

#Anything interesting here?

# weightlength <- pinnipeds.data %>% 
#   filter(Length != 'NA' & Weight != 'NA') %>% filter(Length > 0 & Weight > 0) %>%
#   select(National.Database.Number, Year.of.Observation, Month.of.Observation, Age.Class, Sex, County, Findings.of.Human.Interaction, Interaction.Type, Pinniped.Common.Name, Latitude, Longitude , Length, Length.Units, Weight, Weight.Units) 
# 
# weightlength$Length <- as.numeric(weightlength$Length)
# weightlength$Weight <- as.numeric(weightlength$Weight)
# weightlength$Length.in <- ifelse(weightlength$Length.Units == 'cm', as.integer(weightlength$Length/2.54), 
#                                ifelse(weightlength$Length.Units == 'in', weightlength$Length, ''))
# weightlength$Weight.lbs <- ifelse(weightlength$Weight.Units == 'kg', as.integer(weightlength$Weight/0.453), 
#                                   ifelse(weightlength$Weight.Units == 'lb', weightlength$Weight, ''))
# 
# ggplot(weightlength, aes(Weight.lbs, Length.in)) +
#   geom_point(position = 'jitter') +
#   xlab("Weight (lbs)") + ylab("Length") +
#   plot_theme()
# 
# qplot(weightlength$Weight.lbs)
# qplot(weightlength$Length.in)
# 
# ggplot(weightlength, aes(Weight.lbs)) + geom_histogram(stat = 'identity', binwidth = 20)

```

```{r mapping, echo = FALSE, eval = FALSE}
##MAPPING

pinnipeds.data.latcleaning <- pinnipeds.data %>%
  transform(Longitude = as.numeric(Longitude),
            Latitude = as.numeric(Latitude)) %>%
  filter(Latitude > 49 & Longitude < -123.5) %>%
  select(National.Database.Number, Year.of.Observation, City, County, Latitude, Longitude)

box <- c(-126.7, 41.79, -119.19, 50.078)
pugetbox <- c(-125.5, 46.79, -121.5, 49.28)

pinnipeds.data.mapping <- pinnipeds.data %>% 
  transform(Longitude = as.numeric(Longitude),
            Latitude = as.numeric(Latitude)) %>%
  filter(Longitude != 'NA')

#All strandings - black dots - stamen attempt
# stamen <- get_stamenmap(bbox = c(-126.7, 41.79, -119.19, 50.078), maptype = "terrain", zoom = 5, size = 2, color = "bw")
# 
# ggmap(stamen) +
#    geom_point(data = pinnipeds.data, aes(x = Longitude, y = Latitude)) +
# scale_alpha(range = c(0, 0.3), guide = FALSE) +
#   xlab("") + ylab("") +
#   theme(
#     axis.ticks = element_blank(),
#     axis.text = element_blank())

#All WA OR - all strandings - black dots
ggmap(get_map(location = box, source = "osm")) +
   geom_point(data = pinnipeds.data.mapping, aes(x = Longitude, y = Latitude)) +
scale_alpha(range = c(0, 0.3), guide = FALSE) +
  #xlab("") + ylab("") +
  theme()
    #axis.ticks = element_blank(),
    #axis.text = element_blank())

#Greater Puget Sound all strandings - black dots
ggmap(get_map(location = pugetbox, source = "osm")) +
  geom_point(data = pinnipeds.data.mapping, aes(x = Longitude, y = Latitude), size = 0.7) +
 scale_alpha(range = c(0, 0.3), guide = FALSE) +
  #xlab("") + ylab("") +
  theme(
    legend.key = element_blank(),
    #axis.ticks = element_blank(),
    #axis.text = element_blank(),
    legend.position = 'top',
    panel.border = element_rect(colour = "black", fill = "NA", size = .5))

#All strandings heatmap
ggmap(get_map(location = box, source = "osm")) +
  geom_point(data = pinnipeds.data.mapping, aes(x = Longitude, y = Latitude), size = 0.7)  +
  stat_density2d(data = pinnipeds.data.mapping, aes(x = Longitude, y = Latitude, fill = ..level.., alpha = ..level..), size = 0.01, bins = 100, geom = "polygon") +

  scale_fill_gradient(low = "yellow", high = "red", guide = FALSE) +
  scale_alpha(range = c(0, 0.3), guide = FALSE) +
  xlab("") + ylab("") +
  theme(
    axis.ticks = element_blank(),
    axis.text = element_blank())

#Puget sound heatmap - all strandings
ggmap(get_map(location = "Puget Sound", source = "stamen", maptype = "watercolor")) +
  geom_point(data = pinnipeds.data.mapping, aes(x = Longitude, y = Latitude), size = 0.7)  +
  stat_density2d(data = pinnipeds.data.mapping, aes(x = Longitude, y = Latitude, fill = ..level.., alpha = ..level..), size = 0.01, bins = 100, geom = "polygon") +
  scale_fill_gradient(low = "yellow", high = "red", guide = FALSE) +
  scale_alpha(range = c(0, 0.1), guide = FALSE) +
  xlab("") + ylab("") +
  theme(
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    panel.border = element_rect(colour = "black", fill = "NA", size = .5))

#Oregon coast heatmap - all strandings
ggmap(get_map(location = c(-123.627933, 44.163370), source = "google", maptype = "roadmap", zoom = 7)) +
  geom_point(data = pinnipeds.data.mapping, aes(x = Longitude, y = Latitude), size = 0.7)  +
  stat_density2d(data = pinnipeds.data.mapping, aes(x = Longitude, y = Latitude, fill = ..level.., alpha = ..level..), size = 0.01, bins = 60, geom = "polygon") +

  scale_fill_gradient(low = "yellow", high = "red", guide = FALSE) +
  scale_alpha(range = c(0, 0.3), guide = FALSE)

#Human interactions - dots by HI type
pinniped.HI.map.data <- pinnipeds.data.mapping %>% filter(Findings.of.Human.Interaction == 'Y' & Interaction.Type != 'NA')

ggmap(get_map(location = box, source = "osm")) +
  geom_point(data = pinniped.HI.map.data, aes(x = Longitude, y = Latitude, color = Interaction.Type), size = 0.7) +
scale_alpha(range = c(0, 0.3), guide = FALSE) +
  xlab("") + ylab("") +
  plot_theme(
    legend.key = element_blank(),
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    legend.position = 'top',
    panel.border = element_rect(colour = "black", fill = "NA", size = .5))

```

```{r summary tables}

#Proportion of species all years
species.prop <- pinnipeds.data %>%
  group_by(Pinniped.Common.Name) %>%
  summarize(cnt = n_distinct(National.Database.Number))

species.prop$prop <- round(species.prop$cnt/sum(species.prop$cnt), 2)*100
colnames(species.prop) <- c("Species", "Number", "Percent")

species.prop.table <- write.csv(species.prop, file = "./Figures/species.prop.table.csv", row.names = FALSE)
                  

#Big proportion table for sex

Sex.table <- pinnipeds.data %>%
  group_by(Sex) %>%
  summarize(all.cnt = n_distinct(National.Database.Number))

Sex.table$All.prop <- round(Sex.table$all.cnt/sum(Sex.table$all.cnt), 2)*100

#Adding in HI proportion
Sex.HI.table <- pinnipeds.data %>%
  filter(Findings.of.Human.Interaction == 'Y' & Interaction.Type != 'NA') %>%
  group_by(Sex) %>%
  summarize(HI.cnt = n_distinct(National.Database.Number)) %>%
  merge(Sex.table, by = 'Sex')

Sex.HI.table$HI.prop <- round(Sex.HI.table$HI.cnt/sum(Sex.HI.table$HI.cnt), 2)*100

#prevalence
sex.HI.prev <- pinnipeds.data %>%
  group_by(Sex, Findings.of.Human.Interaction) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  dcast(Sex ~ Findings.of.Human.Interaction, value.var = 'cnt')
sex.HI.prev[is.na(sex.HI.prev)] <- 0
sex.HI.prev <- sex.HI.prev %>%
    transform(Prev.HI = round(Y/(Y+N+CBD), 2)*100) %>%
  select(Sex, Prev.HI) %>%
  merge(Sex.HI.table, by = 'Sex')

#Adding in HI type and merging all three mini tables
Sex.HI.type.table <- pinnipeds.data %>%
  filter(Findings.of.Human.Interaction == 'Y' & Interaction.Type != 'NA') %>%
  group_by(Sex, Interaction.Type) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  dcast(Sex ~ Interaction.Type, value.var = 'cnt') %>%
  transform(Prop.boat = round(Boat/(Boat + Fisheries + Gunshot + Other)*100),
            Prop.fish = round(Fisheries/(Boat + Fisheries + Gunshot + Other)*100),
            Prop.shot = round(Gunshot/(Boat + Fisheries + Gunshot + Other)*100),
            Prop.other = round(Other/(Boat + Fisheries + Gunshot + Other)*100)) %>%
  select(c(Sex, Prop.boat, Prop.fish, Prop.shot, Prop.other)) %>%
  merge(sex.HI.prev, by = 'Sex') %>%
  select(c(Sex, All.prop, Prev.HI, Prop.fish, Prop.shot, Prop.boat, Prop.other))
colnames(Sex.HI.type.table) <- c("Sex", "All Strandings (%)", "Prevalence of HI (%)", "Fisheries Interactions (%)", "Gunshots (%)", "Boat Injuries (%)", "Other (%)")

sex.composition.table <- write.csv(Sex.HI.type.table, file = "./Figures/Sex.composition.table.csv", row.names = FALSE)


#Big table for age class

Age.table <- pinnipeds.data %>%
  #filter(Age.Class != 'Unid') %>%
  group_by(Age.Class) %>%
  summarize(all.cnt = n_distinct(National.Database.Number))

Age.table$All.prop <- round(Age.table$all.cnt/sum(Age.table$all.cnt), 2)*100

#Adding in HI proportion - not using this anymore
# Age.HI.table <- pinnipeds.data %>%
#   filter(Findings.of.Human.Interaction == 'Y' & Interaction.Type != 'NA') %>%
#   #filter(Age.Class != 'Unid') %>%
#   group_by(Age.Class) %>%
#   summarize(HI.cnt = n_distinct(National.Database.Number)) %>%
#   merge(Age.table, by = 'Age.Class')

#Age.HI.table$HI.prop <- round(Age.HI.table$HI.cnt/sum(Age.HI.table$HI.cnt), 2)*100

#Prevalence
age.HI.prev <- pinnipeds.data %>%
  group_by(Age.Class, Findings.of.Human.Interaction) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  dcast(Age.Class ~ Findings.of.Human.Interaction, value.var = 'cnt')
age.HI.prev[is.na(age.HI.prev)] <- 0
age.HI.prev <- age.HI.prev %>%
    transform(Prev.HI = round(Y/(Y+N+CBD), 2)*100) %>%
  merge(Age.table, by = 'Age.Class') %>%
  select(Age.Class, All.prop, Prev.HI)

#Adding in HI type and merging all three mini tables
Age.HI.type.table <- pinnipeds.data %>%
  filter(Findings.of.Human.Interaction == 'Y' & Interaction.Type != 'NA') %>%
  group_by(Age.Class, Interaction.Type) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  dcast(Age.Class ~ Interaction.Type, value.var = 'cnt') %>%
  transform(Prop.boat = round(Boat/(Boat + Fisheries + Gunshot + Other)*100),
            Prop.fish = round(Fisheries/(Boat + Fisheries + Gunshot + Other)*100),
            Prop.shot = round(Gunshot/(Boat + Fisheries + Gunshot + Other)*100),
            Prop.other = round(Other/(Boat + Fisheries + Gunshot + Other)*100)) %>%
  select(c(Age.Class, Prop.boat, Prop.fish, Prop.shot, Prop.other)) %>%
  merge(age.HI.prev, by = 'Age.Class') %>%
  select(c(Age.Class, All.prop, Prev.HI, Prop.fish, Prop.shot, Prop.boat, Prop.other))
colnames(Age.HI.type.table) <- c("Age", "All Strandings (%)", "Prevalence of HI (%)", "Fisheries Interactions (%)", "Gunshots (%)", "Boat Injuries (%)", "Other (%)")

Age.HI.type.table <- Age.HI.type.table[order(Age.HI.type.table$Age),]

age.composition.table <- write.csv(Age.HI.type.table, file = "./Figures/age.composition.table.csv", row.names = FALSE)


#Species and age/sex composition
species.age.props <- pinnipeds.data %>%
  filter(Pinniped.Common.Name != 'Unidentified') %>%
  group_by(Pinniped.Common.Name, Age.Class) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  ggplot(., aes(Age.Class, cnt)) +
  #geom_boxplot() +
    geom_bar(stat = 'identity') +
    xlab("") + ylab("Strandings") +
    facet_wrap(~ Pinniped.Common.Name) +
    pubfigure_theme()

species.sex.props <- pinnipeds.data %>%
  filter(Pinniped.Common.Name != 'Unidentified') %>%
  group_by(Pinniped.Common.Name, Sex) %>%
  summarize(cnt = n_distinct(National.Database.Number))

ggplot(species.sex.props, aes(Pinniped.Common.Name, cnt, fill = Sex)) +
  geom_bar(stat = 'identity', position = 'fill') +
  xlab("") + ylab("Strandings") +
  pubfigure_theme()

formerge <- species.sex.props %>% 
  dcast(Pinniped.Common.Name ~ Sex, value.var = 'cnt') %>%
  transform(Prop.Fem = round(Female/(Female+Male+Unid), 3)*100,
            Prop.Male = round(Male/(Female+Male+Unid), 3)*100) %>%
  select(Pinniped.Common.Name, Prop.Fem, Prop.Male)

species.props <- pinnipeds.data %>%
  filter(Pinniped.Common.Name != 'Unidentified') %>%
  group_by(Pinniped.Common.Name, Age.Class) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  dcast(Pinniped.Common.Name ~ Age.Class, value.var = 'cnt') %>%
  transform(Tot = Pup+Yearling+Subadult+Adult+Unid) %>%
  transform(Prop.pup = round(Pup/(Tot), 3)*100, 
            Prop.year = round(Yearling/(Tot), 3)*100,
            Prop.sub = round(Subadult/(Tot), 3)*100,
            Prop.ad = round(Adult/(Tot), 3)*100,
            Prop.un = round(Unid/(Tot), 3)*100) %>%
  merge(formerge, by = 'Pinniped.Common.Name') %>%
  select(Pinniped.Common.Name, Tot, Prop.Male, Prop.Fem, Prop.pup, Prop.year, Prop.sub, Prop.ad, Prop.un)
colnames(species.props) <- c("Species", "Total (n)", "Male (%)", "Female (%)", "Pup (%)", "Yearling (%)", "Subadult (%)", "Adult (%)", "Unidentified Age (%)")
  
species.age.sex.composition <- write.csv(species.props, file = "./Figures/species.age.sex.composition.csv", row.names = FALSE)

########same but HI - looks very similar to all combined strandings
formerge.HI <- pinnipeds.data %>%
  filter(Pinniped.Common.Name != 'Unidentified' & Findings.of.Human.Interaction == 'Y') %>%
  group_by(Pinniped.Common.Name, Sex) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  dcast(Pinniped.Common.Name ~ Sex, value.var = 'cnt') %>%
  transform(Prop.Fem = round(Female/(Female+Male+Unid), 3)*100,
            Prop.Male = round(Male/(Female+Male+Unid), 3)*100) %>%
  select(Pinniped.Common.Name, Prop.Fem, Prop.Male)

species.props.HI <- pinnipeds.data %>%
  filter(Pinniped.Common.Name != 'Unidentified' & Findings.of.Human.Interaction == 'Y') %>%
  group_by(Pinniped.Common.Name, Age.Class) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  dcast(Pinniped.Common.Name ~ Age.Class, value.var = 'cnt') %>%
  transform(Tot = Pup+Yearling+Subadult+Adult+Unid) %>%
  transform(Prop.pup = round(Pup/(Tot), 3)*100, 
            Prop.year = round(Yearling/(Tot), 3)*100,
            Prop.sub = round(Subadult/(Tot), 3)*100,
            Prop.ad = round(Adult/(Tot), 3)*100,
            Prop.un = round(Unid/(Tot), 3)*100) %>%
  merge(formerge.HI, by = 'Pinniped.Common.Name') %>%
  select(Pinniped.Common.Name, Tot, Prop.Male, Prop.Fem, Prop.pup, Prop.year, Prop.sub, Prop.ad, Prop.un)
```

```{r}
##Species composition table

#It looks like, for example, harbor seals comrpise the majority of all cases, but FI and HI are more evenly distributed across species?

#Big table for species
state.species.prop <- pinnipeds.data %>%
  group_by(Pinniped.Common.Name, State) %>%
  summarize(cnt = n_distinct(National.Database.Number))  %>%
  dcast(Pinniped.Common.Name ~ State, value.var = 'cnt') %>%
  transform(prop.or = round(OR/(OR+WA), 2)*100,
            prop.wa = round(WA/(OR+WA), 2)*100) %>%
  select(Pinniped.Common.Name, prop.or, prop.wa)

# state.species.prop.table <- write.csv(state.species.prop, file = "./Figures/state.species.prop.table.csv", row.names = FALSE)

species.bigtable <- pinnipeds.data %>%
  group_by(Pinniped.Common.Name) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  transform(all.prop = round(cnt/sum(cnt), 2)*100)

# species.HI.bigtable <- pinnipeds.data %>%
#   filter(Findings.of.Human.Interaction == 'Y' & Interaction.Type != 'NA') %>%
#   group_by(Pinniped.Common.Name) %>%
#   summarize(cnt = n_distinct(National.Database.Number)) %>%
#   transform(HI.prop = round(cnt/sum(cnt), 2)*100) %>%
#   merge(species.bigtable, by = 'Pinniped.Common.Name') %>%
#   select(Pinniped.Common.Name, all.prop, HI.prop)

species.HI.prev <- pinnipeds.data %>%
  #filter(Pinniped.Common.Name != 'Unidentified') %>% 
  group_by(Pinniped.Common.Name, Findings.of.Human.Interaction) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  dcast(Pinniped.Common.Name ~ Findings.of.Human.Interaction, value.var = 'cnt')
species.HI.prev[is.na(species.HI.prev)] <- 0
species.HI.prev <- species.HI.prev %>%
    transform(Prev.HI = round(Y/(Y+N+CBD), 2)*100) %>%
  select(Pinniped.Common.Name, Prev.HI) %>%
  merge(species.bigtable, by = 'Pinniped.Common.Name')

species.prop.HI <- pinnipeds.data %>%
  filter(Findings.of.Human.Interaction == 'Y' & Interaction.Type != 'NA') %>%
  group_by(Pinniped.Common.Name, Interaction.Type) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  dcast(Pinniped.Common.Name ~ Interaction.Type, value.var = 'cnt') %>%
  transform(Total = Boat + Gunshot + Fisheries + Other) %>%
  transform(Prop.Boat = round(Boat/Total, 2)*100,
            Prop.Fisheries = round(Fisheries/Total, 2)*100,
            Prop.Gunshot = round(Gunshot/Total, 2)*100,
            Prop.Other = round(Other/Total, 2)*100) %>%
  merge(species.HI.prev, by = 'Pinniped.Common.Name') %>%
  merge(state.species.prop, by = 'Pinniped.Common.Name') %>%
  select(Pinniped.Common.Name, cnt, all.prop, prop.or, prop.wa, Prev.HI, Prop.Fisheries, Prop.Gunshot, Prop.Boat, Prop.Other) 

species.prop.HI[is.na(species.prop.HI)] <- 0

colnames(species.prop.HI) <- c("Species", "Total (n)", "All Strandings (%)", "OR (%)", "WA (%)", "Prevalence of HI (%)", "Fisheries (%)", "Gunshot (%)", "Boat (%)", "Other (%)")

species.HI.prop.table <- write.csv(species.prop.HI, file = "./Figures/species.HI.prop.table.csv", row.names = F)

##Big Prevalence over time Table(s)
##all species combined, interaction types as a proportion of all cases, not just HI cases

numberperyear <- pinnipeds.data %>% 
  group_by(Year.of.Observation) %>%
  summarize(yr.cnt = n_distinct(National.Database.Number))

allprev <- pinnipeds.data %>%
  group_by(Findings.of.Human.Interaction, Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  dcast(Year.of.Observation ~ Findings.of.Human.Interaction, value.var = 'cnt') 
allprev[is.na(allprev)] <- 0
allprev <- allprev %>% transform(HI.Prev = Y/(Y+N+CBD)) %>%
  merge(numberperyear, by = 'Year.of.Observation') %>%
  select(Year.of.Observation, yr.cnt, HI.Prev)

allprev.type <- pinnipeds.data %>%
  group_by(Interaction.Type, Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  dcast(Year.of.Observation ~ Interaction.Type, value.var = 'cnt') 
allprev.type[is.na(allprev.type)] <- 0
allprev.type <- allprev.type %>%
  merge(allprev, by = 'Year.of.Observation') %>%
  transform(Boat = (Boat/yr.cnt), 
            Fisheries = (Fisheries/yr.cnt),
            Gunshot = (Gunshot/yr.cnt),
            Other = (Other/yr.cnt)) %>%
  select(Year.of.Observation, yr.cnt, HI.Prev, Boat, Gunshot, Fisheries, Other)

allprev.stats <- allprev.type %>% 
  select(-c(yr.cnt, HI.Prev)) %>% melt(id.vars = "Year.of.Observation") 

HI.type.prev.figure <- 
  ggplot(allprev.stats, aes(Year.of.Observation, value, group = variable, col = variable)) +
  geom_point() + 
  geom_line() + 
#geom_smooth(method = 'lm', se = F) +
  xlab("") + ylab("Prevalence") +
  pubfigure_theme(legend.position = 'top') + 
  scale_color_brewer(palette = 'Set1')

#Shows increasing significantly just for Other, but negative slope when just variable?! HELP.
summary(lm(value ~ Year.of.Observation*variable, data = allprev.stats))

##individual species
numberperyearperspecies <- pinnipeds.data %>% 
  group_by(Year.of.Observation, Pinniped.Common.Name) %>%
  summarize(yr.cnt = n_distinct(National.Database.Number))

allprev.species <- pinnipeds.data %>%
  group_by(Findings.of.Human.Interaction, Year.of.Observation, Pinniped.Common.Name) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  dcast(Year.of.Observation + Pinniped.Common.Name ~ Findings.of.Human.Interaction, value.var = 'cnt') 
allprev.species[is.na(allprev.species)] <- 0
allprev.species <- allprev.species %>% transform(HI.Prev = Y/(Y+N+CBD)) %>%
  merge(numberperyearperspecies, by = c('Year.of.Observation', 'Pinniped.Common.Name')) %>%
  select(Year.of.Observation, Pinniped.Common.Name, yr.cnt, HI.Prev)

allprev.type.species <- pinnipeds.data %>%
  group_by(Interaction.Type, Year.of.Observation, Pinniped.Common.Name) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  dcast(Year.of.Observation + Pinniped.Common.Name ~ Interaction.Type, value.var = 'cnt') 
allprev.type.species[is.na(allprev.type.species)] <- 0
allprev.type.species <- allprev.type.species %>%
  merge(allprev.species, by = c('Year.of.Observation', 'Pinniped.Common.Name')) %>%
  transform(Boat = (Boat/yr.cnt), 
            Fisheries = (Fisheries/yr.cnt),
            Gunshot = (Gunshot/yr.cnt),
            Other = (Other/yr.cnt)) %>%
  select(Year.of.Observation, Pinniped.Common.Name, HI.Prev, Boat, Gunshot, Fisheries, Other)

allprev.species.stats <- allprev.type.species %>% 
  select(-c(HI.Prev)) %>% 
  melt(id.vars = c("Year.of.Observation", "Pinniped.Common.Name")) %>%
  filter(Pinniped.Common.Name != 'Unidentified')

HI.type.prev.species.figure <- 
  ggplot(allprev.species.stats, aes(Year.of.Observation, value, group = c(Pinniped.Common.Name + variable), col = variable, shape = Pinniped.Common.Name)) +
  geom_point() + 
  #geom_line() +
  geom_smooth(method = 'lm', se = F) +
  xlab("") + ylab("Prevalence") +
  pubfigure_theme(legend.position = 'top') + 
  scale_color_brewer(palette = 'Set1')

#Shows increasing significantly for fisheries for nfs and gfs and decreasing for gunshot wounds, but overall gunshot has positive slope?! HELP.
summary(lm(value ~ Year.of.Observation + Pinniped.Common.Name*variable, data = allprev.species.stats))

#Composition of species for each HI type
# species.prop.HI.2 <- pinnipeds.data %>%
#   filter(Findings.of.Human.Interaction == 'Y' & Interaction.Type != 'NA') %>%
#   group_by(Pinniped.Common.Name, Interaction.Type) %>%
#   summarize(cnt = as.integer(n_distinct(National.Database.Number))) %>%
#   dcast(Interaction.Type ~ Pinniped.Common.Name, value.var = 'cnt')
#
# species.prop.HI.2[is.na(species.prop.HI.2)] <- 0

#chisq.test(species.prop.HI.2)

```


