
---
title: "Pinniped Strandings"
output: 
  word_document: 
    reference_docx: markdownstyledoc.docx
---

```{r include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.width = 4, fig.height = 3.5)
```

```{r load packages, echo = FALSE}

# install.packages("ggmap") 
# install.packages("data.table")
#install.packages("devtools")
library(devtools)
#devtools::install_github("hadley/ggplot2")
#devtools::install_github("adletaw/captioner")
library(tidyr)
library(ggmap)
library(data.table)
library(dplyr)
library(ggplot2)
library(cowplot)
library(stats)
library(scales)
library(captioner)
library(knitr)
library(reshape2)
library(stringr)
library(magrittr)
setwd("~/Documents/R/Strandings")

plot_theme <- function(...) {
  theme(
    #text = element_text(size = 11),
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, color = "black", size = 10), 
    axis.text = element_text(vjust = 0.5, color = "black", size = 10), 
    axis.title = element_text(size = 11),
    axis.line.y = element_line(colour = "black"), 
    axis.line.x = element_line(colour = "black"), 
    plot.background = element_rect(), 
    panel.background = element_blank(), 
    panel.grid = element_blank(), 
    legend.title = element_blank(),
    legend.key = element_blank(),
    legend.text = element_text(size = 8),
    ...)
}

case <- function(x)
  paste0(toupper(substr(x, 1, 1)), tolower(substring(x, 2)))

figs <- captioner(prefix="Figure")
tbls <- captioner(prefix="Table")

# figs("name")
# ## [1] "Figure  1: Caption."
# 
# figs("name",display="cite")
# ## [1] "Figure  1"
# 
# figs("name",display="num")
# ## [1] "1"

```

```{r load pre-cleaned csv for laptop, echo = FALSE}

pinnipeds.data <- read.csv("pinnipeds.data.csv", header = TRUE, na.strings = "", stringsAsFactors = FALSE)

pinnipeds.data$Age.Class <- factor(pinnipeds.data$Age.Class, 
          levels = c("Pup", "Yearling", "Subadult", "Adult", "Unid"))

pinnipeds.data$Month.of.Observation <- factor(pinnipeds.data$Month.of.Observation, 
          levels = c('JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'))

```


```{r ENSO}

#Do more pinnipeds strand (or HI/FI cases) during EN compared to LN conditions?

#All species combined
ENSO.all <- pinnipeds.data %>% 
  filter(Observation.Status == 'ALIVE' | Observation.Status == 'FRESH DEAD') %>%
  group_by(ENSO, Month.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number))

ENSO.all.figure <- 
  ggplot(ENSO.all, aes(x = ENSO, y = cnt, fill = ENSO)) +
  geom_boxplot() +
  xlab(" ") + ylab("Monthly Stranding Cases") +
  scale_y_continuous(labels = comma) +
  plot_theme() +
  scale_fill_brewer(palette = 'Set1')
ggsave(ENSO.species.figure, file = "~/Documents/R/Strandings/Figures/ENSO.all.figure.pdf")

summary(aov(cnt ~ ENSO, data = ENSO.all))


#All species combined - HI
ENSO.HI <- pinnipeds.data %>% 
  filter(Observation.Status == 'ALIVE' | Observation.Status == 'FRESH DEAD') %>%
  filter(Findings.of.Human.Interaction == 'Y') %>%
  group_by(ENSO, Month.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number))

ENSO.HI.figure <- 
  ggplot(ENSO.HI, aes(x = ENSO, y = cnt, fill = ENSO)) +
  geom_boxplot() +
  xlab(" ") + ylab("Monthly Stranding Cases") +
  scale_y_continuous(labels = comma) +
  plot_theme() +
  scale_fill_brewer(palette = 'Set1')
ggsave(ENSO.species.figure, file = "~/Documents/R/Strandings/Figures/ENSO.HI.figure.pdf")

summary(aov(cnt ~ ENSO, data = ENSO.HI))

#All species combined - FI and gunshots
ENSO.Fish <- pinnipeds.data %>% 
  filter(Observation.Status == 'ALIVE' | Observation.Status == 'FRESH DEAD') %>%
  filter(Findings.of.Human.Interaction == 'Y' & 
           Interaction.Type == 'Fisheries' | Interaction.Type == 'Gunshot') %>%
  group_by(ENSO, Month.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number))

ENSO.Fish.figure <- 
  ggplot(ENSO.Fish, aes(x = ENSO, y = cnt, fill = ENSO)) +
  geom_boxplot() +
  xlab(" ") + ylab("Monthly Stranding Cases") +
  scale_y_continuous(labels = comma) +
  plot_theme() +
  scale_fill_brewer(palette = 'Set1')
ggsave(ENSO.species.figure, file = "~/Documents/R/Strandings/Figures/ENSO.Fish.figure.pdf")

#Gunshots sig dif by itself, and combined = sig, fisheries not sig dif alone
summary(aov(cnt ~ ENSO, data = ENSO.Fish))

#Boxplot per EN/LN per species

ENSO.species <- pinnipeds.data %>% 
  filter(Pinniped.Common.Name != 'Unidentified') %>%
  filter(Observation.Status == 'ALIVE' | Observation.Status == 'FRESH DEAD') %>%
  group_by(Pinniped.Common.Name, ENSO, Month.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number))

ENSO.species.figure <- 
  ggplot(ENSO.species, aes(x = Pinniped.Common.Name, y = cnt, fill = ENSO)) +
  geom_boxplot() +
  xlab(" ") + ylab("Monthly Stranding Cases") +
  scale_y_continuous(labels = comma) +
  plot_theme() +
  scale_fill_brewer(palette = 'Set1')
ggsave(ENSO.species.figure, file = "~/Documents/R/Strandings/Figures/ENSO.species.figure.pdf")

#Suggests no difference in strandings between EN/LN
summary(aov(cnt ~ Pinniped.Common.Name + ENSO, data = ENSO.species))

##THIS NEEDS HELP
##Trying to do anova.... does it matter if I just have total EN/LN per species, or whether the anova (I'm assuming) takes an average of the monthly EN/LN count (output is different if I use ENSO.species vs ENSO.anova)
# ENSO.species.anova <- pinnipeds.data %>%
#   group_by(Pinniped.Common.Name, ENSO) %>%
#   summarize(cnt = n_distinct(National.Database.Number))
# 
# summary(aov(cnt ~ Pinniped.Common.Name + ENSO, data = ENSO.species.anova))
# #Help - why no p values
# TukeyHSD(aov(cnt ~ ENSO + Pinniped.Common.Name*ENSO, data = ENSO.species.anova))

##HELP! How do I show that for EACH species, is there a difference between LN/EN?? t or lapply pairwise for each species? Doesn't look like there is a difference
CSL <- ENSO.species %>% filter(Pinniped.Common.Name == 'California sea lion') 
pairwise.t.test(CSL$cnt, CSL$ENSO)

HS <- ENSO.species %>% filter(Pinniped.Common.Name == 'Harbor seal') 
pairwise.t.test(HS$cnt, HS$ENSO)

```

```{r all HI FI ENSO categorical}

#HI strandings
ENSO.species.HI <- pinnipeds.data %>% 
  filter(Findings.of.Human.Interaction == 'Y' & Pinniped.Common.Name != 'Unidentified') %>%
  filter(Observation.Status == 'ALIVE' | Observation.Status == 'FRESH DEAD') %>%
  group_by(Pinniped.Common.Name, ENSO, Month.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number))

ENSO.species.HI.figure <- 
  ggplot(ENSO.species.HI, aes(x = Pinniped.Common.Name, y = cnt, fill = ENSO)) +
  geom_boxplot() +
  xlab(" ") + ylab("Monthly Human Interaction Cases") +
  plot_theme() +
  scale_fill_brewer(palette = 'Set1')
ggsave(ENSO.species.HI.figure, file = "~/Documents/R/Strandings/Figures/ENSO.species.HI.figure.pdf")

##Same as above for all cases - needs help
# summary(aov(cnt ~ Pinniped.Common.Name + ENSO, data = ENSO.species.HI))
# 
CSL <- ENSO.species.HI %>% filter(Pinniped.Common.Name == 'California sea lion')
pairwise.t.test(CSL$cnt, CSL$ENSO)

HS <- ENSO.species.HI %>% filter(Pinniped.Common.Name == 'Harbor seal')
pairwise.t.test(HS$cnt, HS$ENSO)

#FI
ENSO.species.FI <- pinnipeds.data %>% 
  filter(Fishery.Interaction == 'Y' | Shot == 'Y') %>%
  filter(Pinniped.Common.Name != 'Unidentified') %>%
  filter(Observation.Status == 'ALIVE' | Observation.Status == 'FRESH DEAD') %>%
  group_by(Pinniped.Common.Name, ENSO, Month.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number))

ENSO.species.FI.figure <- ggplot(ENSO.species.FI, aes(x = Pinniped.Common.Name, y = cnt, fill = ENSO)) +
  geom_boxplot() +
  xlab(" ") + ylab("Monthly Fisheries Interaction and Gunshot Cases") +
  plot_theme() +
  scale_fill_brewer(palette = 'Set1')
ggsave(ENSO.species.FI.figure, file = "~/Documents/R/Strandings/Figures/ENSO.species.FI.figure.pdf")

##Same as above for all cases - needs help
summary(aov(cnt ~ Pinniped.Common.Name + ENSO, data = ENSO.species.FI))

CSL <- ENSO.species.FI %>% filter(Pinniped.Common.Name == 'California sea lion')
pairwise.t.test(CSL$cnt, CSL$ENSO)

HS <- ENSO.species.FI %>% filter(Pinniped.Common.Name == 'Harbor seal')
pairwise.t.test(HS$cnt, HS$ENSO)
```

```{r all cases HI FI numeric MEI, eval = FALSE, echo = FALSE}
#Regression with numeric MEI - all cases

basic.regression <- pinnipeds.data %>%
  #filter(Pinniped.Common.Name == 'Harbor seal') %>%
  group_by(MEI) %>%
  summarize(cnt = n_distinct(National.Database.Number))

ggplot(basic.regression, aes(MEI, cnt)) +
  geom_point(position = 'identity') +
  geom_smooth(method = "lm") +
  plot_theme()

summary(lm(MEI ~ cnt, data = basic.regression))

#Regression with numeric MEI - HI

basic.regression.HI <- pinnipeds.data %>%
  filter(Findings.of.Human.Interaction == 'Y') %>%
  group_by(MEI) %>%
  summarize(cnt = n_distinct(National.Database.Number))

ggplot(basic.regression.HI, aes(MEI, cnt)) +
  geom_point(position = 'jitter') +
  geom_smooth(method = "lm") +
  plot_theme()

summary(lm(MEI ~ cnt, data = basic.regression.HI))

#Regression with numeric MEI - FI

basic.regression.FI <- pinnipeds.data %>%
  filter(Fishery.Interaction == 'Y' | Shot == 'Y') %>%
  group_by(MEI) %>%
  summarize(cnt = n_distinct(National.Database.Number))

ggplot(basic.regression.FI, aes(MEI, cnt)) +
  geom_point(position = 'jitter') +
  geom_smooth(method = "lm") +
  plot_theme()

summary(lm(MEI ~ cnt, data = basic.regression.FI))

```

```{r numeric MEI for each species, eval = FALSE, echo = FALSE}

#Higher strandings for any of the species during ENSO?
species.regression <- pinnipeds.data %>%
   group_by(MEI, Pinniped.Common.Name) %>%
   summarize(cnt = n_distinct(National.Database.Number))

 ggplot(species.regression, aes(MEI, cnt, group = Pinniped.Common.Name, col = Pinniped.Common.Name)) +
   geom_point(position = 'jitter') +
   geom_smooth(method = "lm", se = F) +
   plot_theme(legend.position = 'top') +
   scale_color_brewer(palette = 'Set1')

#summary(lm(cnt ~ Pinniped.Common.Name + MEI, data = species.regression))
```

```{r all strandings over time}

#Are the number of cases of all combined species increasing or decreasing over time?

data.by.year <- pinnipeds.data %>% 
  group_by(Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number)) 

#Statistically significant change in all stranding cases in OR and WA combined over time (p < 0.05, 25 strandings per year increase).
summary(lm(cnt ~ Year.of.Observation, data = data.by.year))

all.yr.figure <- 
  ggplot(data.by.year, aes(x = Year.of.Observation, y = cnt)) + 
  geom_point(position = "identity") +
  geom_smooth(method = "lm", se = FALSE, col = 'black', linetype = 3) +
  xlab("") + ylab("Annual Strandings") +
  scale_y_continuous(labels = comma) +
  plot_theme() +
  scale_color_brewer(palette = 'Set1') 
ggsave(all.yr.figure, file = "~/Documents/R/Strandings/Figures/all.year.figure.pdf")

```

```{r HI and FI number of cases over time}

#Are the number of HI cases of all combined species increasing or decreasing over time?

HI.by.year <- pinnipeds.data %>%
  filter(Findings.of.Human.Interaction == 'Y') %>%
  group_by(Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number)) 

#Regression shows significant increase (6/yr) of all HI cases, p < 0.05
summary(lm(cnt ~ Year.of.Observation, data = HI.by.year))

#anova confirms years are different, p-val < 0.05
summary(aov(cnt ~ Year.of.Observation, data = HI.by.year))

HI.year.figure <- 
  ggplot(HI.by.year, aes(x = Year.of.Observation, y = cnt)) + 
  geom_point(position = "identity") +
  geom_smooth(method = "lm", se = FALSE, col = 'black', linetype = 3) +
  xlab("") + ylab("Annual Human Interaction Cases") +
  scale_y_continuous(labels = comma) +
  #scale_x_continuous(breaks = c(1989:2015)) +
  plot_theme(legend.position = 'top') +
  scale_color_brewer(palette = 'Set1')
ggsave(HI.year.figure, file = "~/Documents/R/Strandings/Figures/HI.year.figure.pdf")
```

```{r HI types over time}
#Are specific types of HI cases changing over time?

HI.by.year.type <- pinnipeds.data %>%
  filter(Findings.of.Human.Interaction == 'Y' & Interaction.Type != 'NA') %>%
  group_by(Interaction.Type, Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number)) 

#Regression shows there is an effect of year for all HI types, that they are increasing over time (gunshot by 22/yr).
summary(lm(cnt ~ Year.of.Observation + Interaction.Type, data = HI.by.year.type))

#Tukey shows average annual HI types are not all different from one another
TukeyHSD(aov(cnt ~ Interaction.Type, data = HI.by.year.type))

HI.type.year.figure <- 
  ggplot(HI.by.year.type, aes(x = Year.of.Observation, y = cnt, 
                              group = Interaction.Type, col = Interaction.Type)) + 
  geom_point(position = "identity") +
  geom_smooth(method = "lm", se = FALSE) +
  xlab("") + ylab("Human Interaction Cases") +
  plot_theme(legend.position = 'top') + 
  scale_color_brewer(palette = 'Set1')
ggsave(HI.type.year.figure, file = "~/Documents/R/Strandings/Figures/HI.type.year.figure.pdf")

```

```{r monthly all HI FI}

#Are there seasonal patterns in all stranding cases? Only alive and fresh dead because timing matters - hard to tell when decomposed individuals stranded
monthly.all <- pinnipeds.data %>%
  filter(Observation.Status == 'ALIVE' | Observation.Status == 'FRESH DEAD') %>%
  group_by(Year.of.Observation, Month.of.Observation, Sex, Age.Class) %>%
  summarize(cnt = n_distinct(National.Database.Number))

#Help - does this show that Aug, Dec, Jun, July, May, Oct, Sep are different from one another?
summary(lm(cnt ~ Month.of.Observation, data = monthly.all))

#Overall anova and pairwise tests show that there is a seasonal peak (ie some months are different than others)
TukeyHSD(aov(cnt ~ Month.of.Observation, data = monthly.all))
#pairwise.t.test(monthly.all$cnt, monthly.all$Month.of.Observation, p.adj = "none")

#All monthly cases by sex
monthly.sex.figure <- 
  monthly.all %>% group_by(Month.of.Observation, Sex) %>%
  summarize(sum = sum(cnt)) %>%
ggplot(aes(x = factor(Month.of.Observation), y = sum, fill = Sex)) +
  geom_bar(stat = 'identity') +
  ylab("Total Strandings") + xlab("") + 
  scale_y_continuous(labels = comma) +
  plot_theme(legend.position = 'top') + 
  scale_fill_brewer(palette = 'Set1')
ggsave(monthly.sex.figure, file = "~/Documents/R/Strandings/Figures/monthly.sex.figure.pdf")

#Monthly strandings by age class
monthly.age.figure <- monthly.all %>% 
  group_by(Month.of.Observation, Age.Class) %>%
  summarize(sum = sum(cnt)) %>%
  ggplot(aes(x = factor(Month.of.Observation), y = sum, fill = as.factor(Age.Class))) +
  geom_bar(stat = 'identity') +
  ylab("Total Strandings") + xlab("") + 
  scale_y_continuous(labels = comma) +
  plot_theme(legend.position = 'top', 
             legend.text = element_text(size = 8)) + 
  scale_fill_brewer(palette = 'Set3')
ggsave(monthly.age.figure, file = "~/Documents/R/Strandings/Figures/monthly.age.figure.pdf")

#Peaks by the years
monthly.years.figure <- 
  ggplot(monthly.all, aes(x = factor(Month.of.Observation), y = cnt, 
        group = factor(Year.of.Observation), color = factor(Year.of.Observation))) +
  #geom_area() +
  geom_line(aes(group = factor(Year.of.Observation))) + 
  #geom_smooth(se = F) +
  ylab("Strandings per Month") + xlab("") + 
  scale_y_continuous(labels = comma) +
  plot_theme() #+ 
  #scale_color_brewer()
ggsave(monthly.years.figure, file = "~/Documents/R/Strandings/Figures/monthly.years.figure.pdf")

#Are there seasonal patterns in HI cases?

monthly.HI <- pinnipeds.data %>%
  filter(Findings.of.Human.Interaction == 'Y') %>%
  group_by(Month.of.Observation, Year.of.Observation, Interaction.Type, Sex, Age.Class) %>%
  summarize(cnt = n_distinct(National.Database.Number))

monthly.HI.yr.mo <- pinnipeds.data %>%
  filter(Findings.of.Human.Interaction == 'Y') %>%
  group_by(Month.of.Observation, Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number))

#Regression shows different in Jan and summer
summary(lm(cnt ~ Month.of.Observation, data = monthly.HI.yr.mo))

summary(aov(cnt ~ Month.of.Observation, data = monthly.HI.yr.mo))

monthly.HI.YNCBD <- pinnipeds.data %>% 
  group_by(Findings.of.Human.Interaction, Month.of.Observation) %>% 
  summarize(cnt = n_distinct(National.Database.Number)) 

monthly.HI.YNCBD.prop <- pinnipeds.data %>% 
  group_by(Findings.of.Human.Interaction, Month.of.Observation) %>% 
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  dcast(Month.of.Observation ~ Findings.of.Human.Interaction, value.var = 'cnt') %>%
  transform(prop.Y = round(Y/(CBD+N+Y), 2)*100)

#Bar chart showing proportion of Y, N, and CBD HI cases
ggplot(monthly.HI.YNCBD, aes(x = factor(Month.of.Observation), y = cnt, fill = Findings.of.Human.Interaction)) +
  geom_bar(stat = 'identity') + 
  ylab("Total Human Interaction Cases") + xlab("") + 
  plot_theme(legend.position = 'top') + 
  scale_fill_brewer(palette = 'Set1') 

#Bar chart showing only HI cases - sum of total ever cases in each month
monthly.HI.figure <- monthly.HI %>%
  group_by(Month.of.Observation) %>%
  summarize(cnt = sum(cnt)) %>%
  ggplot(aes(x = factor(Month.of.Observation), y = cnt)) +
  geom_bar(stat = 'identity') +
  ylab("Total Human Interaction Cases") + xlab("") +
  scale_y_continuous(labels = comma) +
  plot_theme() + 
  scale_fill_brewer(palette = 'Set1')
ggsave(monthly.HI.figure, file = "~/Documents/R/Strandings/Figures/monthly.HI.figure.pdf")

#Bar chart showing monthly strandings by interaction type
monthly.HI.figure.stacked <- monthly.HI %>% 
  filter(Interaction.Type != 'NA') %>%
  group_by(Month.of.Observation, Interaction.Type) %>%
  summarize(sum = sum(cnt)) %>%
  ggplot(aes(x = factor(Month.of.Observation), y = sum, fill = Interaction.Type)) +
  geom_bar(stat = 'identity') +
  ylab("Total Human Interaction Cases") + xlab("") + 
  plot_theme(legend.position = 'top') + 
  scale_fill_brewer(palette = 'Set1')
ggsave(monthly.HI.figure.stacked, file = "~/Documents/R/Strandings/Figures/monthly.HI.figure.stacked.pdf")

#Bar chart showing monthly strandings by sex
monthly.HI %>% group_by(Month.of.Observation, Sex) %>%
  summarize(sum = sum(cnt)) %>%
ggplot(aes(x = factor(Month.of.Observation), y = sum, fill = Sex)) +
  geom_bar(stat = 'identity') +
  ylab("Total Human Interaction Cases") + xlab("") + 
  plot_theme(legend.position = 'top') + 
  scale_fill_brewer(palette = 'Set1')

#Monthly HI strandings by age class
monthly.HI.age.figure <- monthly.HI %>% group_by(Month.of.Observation, Age.Class) %>%
  summarize(sum = sum(cnt)) %>%
ggplot(aes(x = factor(Month.of.Observation), y = sum, fill = Age.Class)) +
  geom_bar(stat = 'identity') +
  ylab("Total Human Interaction Cases") + xlab("") + 
  plot_theme(legend.position = 'top') + 
  scale_fill_brewer(palette = 'Set1')
ggsave(monthly.HI.age.figure, file = "~/Documents/R/Strandings/Figures/monthly.HI.age.figure.pdf")

#Peaks by the years
monthly.HI.year.figure <- 
  ggplot(monthly.HI, aes(x = factor(Month.of.Observation), y = cnt, group = factor(Year.of.Observation), color = factor(Year.of.Observation))) +
  #geom_line(aes(group = factor(Year.of.Observation))) + 
  geom_smooth(se = F) +
  ylab("Monthly Human Interaction Cases") + xlab("") + 
  plot_theme() #+ 
  #scale_color_brewer(palette = 'Set3')
ggsave(monthly.HI.year.figure, file = "~/Documents/R/Strandings/Figures/monthly.HI.year.figure.pdf")

#Is there an effect of month on FI?
monthly.FI <- pinnipeds.data %>%
  filter(Fishery.Interaction == 'Y') %>%
  group_by(Year.of.Observation, Month.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number))

#Regression output shows some months dif than others
summary(lm(cnt ~ Month.of.Observation, data = monthly.FI))

summary(aov(cnt ~ Month.of.Observation, data = monthly.FI))

#Peaks by the years
monthly.FI.year.figure <- 
  ggplot(monthly.FI, aes(x = factor(Month.of.Observation), y = cnt, 
              group = factor(Year.of.Observation), color = factor(Year.of.Observation))) +
  geom_line(aes(group = factor(Year.of.Observation))) + 
  geom_smooth(se = F) +
  ylab("Monthly Fisheries Interactions") + xlab("") + 
  plot_theme() #+ 
 # scale_color_brewer(palette = 'Set3')
ggsave(monthly.FI.year.figure, file = "~/Documents/R/Strandings/Figures/monthly.FI.year.figure.pdf")
```

```{r spatial state}
#All by state
year.month.state <- pinnipeds.data %>%
  group_by(State, Year.of.Observation, Month.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number))

year.state.boxplot <- 
  ggplot(year.month.state, aes(x = as.factor(Year.of.Observation), y = cnt, fill = State)) +
  geom_boxplot() +
  xlab("") + ylab("Monthly Strandings") +
  plot_theme(legend.position = 'top') +
  scale_fill_brewer(palette = 'Set1')
ggsave(year.state.boxplot, file = "~/Documents/R/Strandings/Figures/year.state.boxplot.pdf")

year.state.prop <- pinnipeds.data %>%
  group_by(State, Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  dcast(Year.of.Observation ~ State, value.var = 'cnt') %>%
  transform(prop.or = round(OR/(OR+WA), 2)*100)
  
mean(year.state.prop$prop.or)
sum(year.state.prop$OR)/sum(year.state$cnt)

#When accounting for differences across years, states are different
summary(lm(cnt ~ Year.of.Observation + State, year.month.state))

#Tukey - average annual strandings in states are significantly different from each other
summary(aov(cnt ~ Year.of.Observation + State, data = year.month.state))

#Bar chart of strandings by state shows slightly more in WA, but similar trends through time. Higher in OR in 2015 and higher in WA in 2010.
all.state.figure <- pinnipeds.data %>% 
  group_by(State, Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
ggplot(aes(x = factor(Year.of.Observation), y = cnt, fill = State)) +
  geom_bar(stat = 'identity', position = position_dodge(width = 0.8), width = 0.6) + 
   ylab("Total Annual Strandings") + xlab("") + 
   plot_theme() + 
   scale_fill_brewer(palette = 'Set1') 
ggsave(all.state.figure, file = "~/Documents/R/Strandings/Figures/all.state.figure.pdf")

#HI by state
HI.year.state <- pinnipeds.data %>%
  filter(Findings.of.Human.Interaction == 'Y' & Interaction.Type != 'NA') %>%
  group_by(State, Year.of.Observation, Interaction.Type) %>%
  summarize(cnt = n_distinct(National.Database.Number))

HI.state.prop <- HI.year.state %>%
  group_by(State, Interaction.Type) %>%
  summarize(cnt = sum(cnt)) %>%
  dcast(Interaction.Type ~ State, value.var = 'cnt') %>%
  transform(prop.or = round(OR/(OR+WA), 2)*100)
  
mean(HI.state.prop$prop.or)
sum(HI.state.prop$OR)/sum(HI.year.state$cnt)

#When accounting for differences across years, states are different
summary(lm(cnt ~ Year.of.Observation + State, HI.year.state))

#Tukey - average annual strandings in states are significantly different from each other
summary(aov(cnt ~ Year.of.Observation + State, data = HI.year.state))

#Bar chart of HI strandings by state shows growing number in OR
HI.state.year.figure <- pinnipeds.data %>% 
  filter(Findings.of.Human.Interaction == 'Y' & Interaction.Type != 'NA') %>%
  group_by(State, Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
    
ggplot(aes(x = factor(Year.of.Observation), y = cnt, fill = State)) +
  geom_bar(stat = 'identity', position = position_dodge(width = 0.8), width = 0.6) + 
   ylab("Annual Human Interaction Cases") + xlab("") + 
   plot_theme() + 
   scale_fill_brewer(palette = 'Set1') 
ggsave(HI.state.year.figure, file = "~/Documents/R/Strandings/Figures/HI.state.year.figure.pdf")

#Species by state

state.species <- pinnipeds.data %>%
  filter(Pinniped.Common.Name != 'Unidentified') %>%
  group_by(Pinniped.Common.Name, State) %>%
  summarize(cnt = n_distinct(National.Database.Number)) 

#Bar chart
state.species.prop.figure <- 
  ggplot(state.species, aes(Pinniped.Common.Name, cnt, fill = State)) + 
  geom_bar(stat = 'identity', position = position_dodge(width = 0.8), width = 0.6) +
  xlab("") + ylab("Total Strandings") +
  scale_y_continuous(labels = comma) +
  plot_theme() + 
   scale_fill_brewer(palette = 'Set1')
ggsave(state.species.prop.figure, file = "~/Documents/R/Strandings/Figures/state.species.prop.figure.pdf")

#100% stacked
state.species.prop.figure <- 
  ggplot(state.species, aes(Pinniped.Common.Name, cnt, fill = State)) + 
  geom_bar(stat = 'identity', position = 'fill') +
  xlab("") + ylab("Proportion of Strandings") +
  plot_theme() + 
   scale_fill_brewer(palette = 'Set1')
ggsave(state.species.prop.figure, file = "~/Documents/R/Strandings/Figures/state.species.prop.figure.pdf")

```

```{r WA counties}
#all strandings by county - WA

allWA.bycounty <- pinnipeds.data %>% 
  filter(County != 'NA' & County != 'Unknown' & State == 'WA') %>% 
  group_by(County, Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number)) 

allWA.bycounty.figure <- ggplot(allWA.bycounty, aes(x = County, y = cnt)) + 
  geom_bar(stat = 'identity')  + 
  ylab("Total Strandings") + xlab("") + 
  scale_y_continuous(labels = comma) +
  plot_theme() + 
  scale_fill_brewer(palette = 'Set1')
ggsave(allWA.bycounty.figure, file = "~/Documents/R/Strandings/Figures/allWA.bycounty.figure.pdf")

#Some counties have higher/lower strandings compared to others
summary(aov(cnt ~ County, allWA.bycounty))

#Increasing in Pierce, San Juan, Grays Harbor, decreasing in Clark, Mason, Skagit?
summary(lm(cnt ~ County + Year.of.Observation, allWA.bycounty))


#all HI by county - WA

WAHI.bycounty <- pinnipeds.data %>% 
  filter(County != 'NA' & State == 'WA' & 
           Findings.of.Human.Interaction == 'Y' & 
           Interaction.Type != 'NA') %>% 
  group_by(County, Interaction.Type, Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number))

WAHI.bycounty.figure <- 
  ggplot(WAHI.bycounty, aes(x = County, y = cnt, fill = Interaction.Type)) + 
  geom_bar(stat = 'identity')  + 
  ylab("Total Human Interaction Cases") + xlab("") + 
  scale_y_continuous(labels = comma) +
  plot_theme(legend.position = 'top') + 
  scale_fill_brewer(palette = 'Set1') 
ggsave(WAHI.bycounty.figure, file = "~/Documents/R/Strandings/Figures/WAHI.bycounty.figure.pdf")

#Interaction types different
summary(aov(cnt ~ County + Interaction.Type + Year.of.Observation, WAHI.bycounty))

#Does this by by any chance show that Pacific, Pierce, and Gunshots are increasing over time??
summary(lm(cnt ~ County + Interaction.Type + Year.of.Observation, WAHI.bycounty))

```

```{r OR counties}

#all strandings by county - OR

allOR.bycounty <- pinnipeds.data %>% 
  filter(County != 'NA' & County != 'Unknown' & State == 'OR') %>% 
  group_by(County, Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number))

allOR.bycounty.figure <- 
  ggplot(allOR.bycounty, aes(x = County, y = cnt)) + 
  geom_bar(stat = 'identity')  + 
  ylab("Total Strandings") + xlab("") + 
  scale_y_continuous(labels = comma) +
  plot_theme() + 
  scale_fill_brewer(palette = 'Set1')
ggsave(allOR.bycounty.figure, file = "~/Documents/R/Strandings/Figures/allOR.bycounty.figure.pdf")

#Significant differences across counties
summary(aov(cnt ~ County, allOR.bycounty))

#Increasing in Clatsop, Coos, and Lincoln
summary(lm(cnt ~ County + Year.of.Observation, allOR.bycounty))

#all HI by county - OR

ORHI.bycounty <- pinnipeds.data %>% 
  filter(County != 'NA' & State == 'OR' & 
           Findings.of.Human.Interaction == 'Y' & 
           Interaction.Type != 'NA') %>% 
  group_by(County, Interaction.Type, Year.of.Observation) %>%
  summarize(cnt = n_distinct(National.Database.Number)) 
  
ORHI.bycounty.figure <- 
  ggplot(ORHI.bycounty, aes(x = County, y = cnt, fill = Interaction.Type)) + 
  geom_bar(stat = 'identity')  + 
  ylab("Human Interaction Cases") + xlab("") + 
  plot_theme(legend.position = 'top') + 
  scale_fill_brewer(palette = 'Set1')
ggsave(ORHI.bycounty.figure, file = "~/Documents/R/Strandings/Figures/ORHI.bycounty.figure.pdf")

#Interaction types different
#HELP need to refocus here - looking to show which counties in which types are increasing or decreasing over time.
# summary(aov(cnt ~ County + Interaction.Type + Year.of.Observation, ORHI.bycounty))
# TukeyHSD(aov(cnt ~ County + Interaction.Type + Year.of.Observation, ORHI.bycounty))
# summary(lm(cnt ~ County + Interaction.Type + Year.of.Observation, ORHI.bycounty))

```

```{r big counties tables}

#Washington
bigtable.WA <- pinnipeds.data %>% 
  filter(County != 'NA' & State == 'WA' & County != 'Unknown') %>% 
  group_by(County) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  transform(all.prop = round(cnt/sum(cnt), 2)*100)

bigtable.WA.HI <- pinnipeds.data %>% 
  filter(County != 'NA' & State == 'WA' & County != 'Unknown' & 
           Findings.of.Human.Interaction == 'Y' & 
           Interaction.Type != 'NA') %>% 
  group_by(County) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  transform(HI.prop = round(cnt/sum(cnt), 2)*100) %>%
  merge(bigtable.WA, by = 'County')

bigtable.WA.HI.type <- pinnipeds.data %>% 
  filter(County != 'NA' & State == 'WA' & County != 'Unknown' &
           Findings.of.Human.Interaction == 'Y' & 
           Interaction.Type != 'NA') %>% 
  group_by(County, Interaction.Type) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  dcast(County ~ Interaction.Type, value.var = 'cnt') 

bigtable.WA.HI.type[is.na(bigtable.WA.HI.type)] <- 0

bigtable.WA.HI.table <- bigtable.WA.HI.type %>%
  transform(Prop.boat = round(Boat/(Boat + Fisheries + Gunshot + Other)*100),
            Prop.fish = round(Fisheries/(Boat + Fisheries + Gunshot + Other)*100),
            Prop.shot = round(Gunshot/(Boat + Fisheries + Gunshot + Other)*100),
            Prop.other = round(Other/(Boat + Fisheries + Gunshot + Other)*100)) %>%
  select(County, Prop.boat, Prop.fish, Prop.shot, Prop.other) %>%
  merge(bigtable.WA.HI, by = 'County') %>%
  select(County, all.prop, HI.prop, Prop.fish, Prop.shot, Prop.boat, Prop.other)
colnames(bigtable.WA.HI.table) <- c("County", "All Strandings (%)", "Human Interactions (%)", "Fisheries (%)", "Gunshot (%)", "Boat (%)", "Other (%)")

WAcounties.table <- write.csv(bigtable.WA.HI.table, file = "~/Documents/R/Strandings/Figures/WAcounties.table.csv", row.names = F)


#OR
bigtable.OR <- pinnipeds.data %>% 
  filter(County != 'NA' & State == 'OR' & County != 'Unknown') %>% 
  group_by(County) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  transform(all.prop = round(cnt/sum(cnt), 2)*100)

bigtable.OR.HI <- pinnipeds.data %>% 
  filter(County != 'NA' & State == 'OR' & County != 'Unknown' &
           Findings.of.Human.Interaction == 'Y' & 
           Interaction.Type != 'NA') %>% 
  group_by(County) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  transform(HI.prop = round(cnt/sum(cnt), 2)*100) %>%
  merge(bigtable.OR, by = 'County')

bigtable.OR.HI.type <- pinnipeds.data %>% 
  filter(County != 'NA' & State == 'OR' & County != 'Unknown' &
           Findings.of.Human.Interaction == 'Y' & 
           Interaction.Type != 'NA') %>% 
  group_by(County, Interaction.Type) %>%
  summarize(cnt = n_distinct(National.Database.Number)) %>%
  dcast(County ~ Interaction.Type, value.var = 'cnt') 

bigtable.OR.HI.type[is.na(bigtable.OR.HI.type)] <- 0

bigtable.OR.HI.table <- bigtable.OR.HI.type %>%
  transform(Prop.boat = round(Boat/(Boat + Fisheries + Gunshot + Other)*100),
            Prop.fish = round(Fisheries/(Boat + Fisheries + Gunshot + Other)*100),
            Prop.shot = round(Gunshot/(Boat + Fisheries + Gunshot + Other)*100),
            Prop.other = round(Other/(Boat + Fisheries + Gunshot + Other)*100)) %>%
  select(County, Prop.boat, Prop.fish, Prop.shot, Prop.other) %>%
  merge(bigtable.OR.HI, by = 'County') %>%
  select(County, all.prop, HI.prop, Prop.fish, Prop.shot, Prop.boat, Prop.other)
colnames(bigtable.OR.HI.table) <- c("County", "All Strandings (%)", "Human Interactions (%)", "Fisheries (%)", "Gunshot (%)", "Boat (%)", "Other (%)")

ORcounties.table <- write.csv(bigtable.OR.HI.table, file = "~/Documents/R/Strandings/Figures/ORcounties.table.csv", row.names = F)
```

```{r weight length, eval = FALSE, echo = FALSE}

#Anything interesting here?

# weightlength <- pinnipeds.data %>% 
#   filter(Length != 'NA' & Weight != 'NA') %>% filter(Length > 0 & Weight > 0) %>%
#   select(National.Database.Number, Year.of.Observation, Month.of.Observation, Age.Class, Sex, County, Findings.of.Human.Interaction, Interaction.Type, Pinniped.Common.Name, Latitude, Longitude , Length, Length.Units, Weight, Weight.Units) 
# 
# weightlength$Length <- as.numeric(weightlength$Length)
# weightlength$Weight <- as.numeric(weightlength$Weight)
# weightlength$Length.in <- ifelse(weightlength$Length.Units == 'cm', as.integer(weightlength$Length/2.54), 
#                                ifelse(weightlength$Length.Units == 'in', weightlength$Length, ''))
# weightlength$Weight.lbs <- ifelse(weightlength$Weight.Units == 'kg', as.integer(weightlength$Weight/0.453), 
#                                   ifelse(weightlength$Weight.Units == 'lb', weightlength$Weight, ''))
# 
# ggplot(weightlength, aes(Weight.lbs, Length.in)) +
#   geom_point(position = 'jitter') +
#   xlab("Weight (lbs)") + ylab("Length") +
#   plot_theme()
# 
# qplot(weightlength$Weight.lbs)
# qplot(weightlength$Length.in)
# 
# ggplot(weightlength, aes(Weight.lbs)) + geom_histogram(stat = 'identity', binwidth = 20)

```

```{r mapping, echo = FALSE, eval = FALSE}
##MAPPING

box <- c(-126.7, 41.79, -119.19, 50.078)
pugetbox <- c(-125.5, 46.79, -121.5, 49.28)

#All strandings - black dots - stamen attempt
# stamen <- get_stamenmap(bbox = c(-126.7, 41.79, -119.19, 50.078), maptype = "terrain", zoom = 5, size = 2, color = "bw")
# 
# ggmap(stamen) +
#    geom_point(data = pinnipeds.data, aes(x = Longitude, y = Latitude)) +
# scale_alpha(range = c(0, 0.3), guide = FALSE) +
#   xlab("") + ylab("") +
#   theme(
#     axis.ticks = element_blank(),
#     axis.text = element_blank())

#All WA OR - all strandings - black dots
ggmap(get_map(location = box, source = "stamen", maptype = "terrain")) +
   geom_point(data = pinnipeds.data, aes(x = Longitude, y = Latitude)) +
scale_alpha(range = c(0, 0.3), guide = FALSE) +
  xlab("") + ylab("") +
  theme(
    axis.ticks = element_blank(),
    axis.text = element_blank())

#Greater Puget Sound all strandings - black dots
ggmap(get_map(location = pugetbox, source = "osm")) +
  geom_point(data = pinnipeds.data, aes(x = Longitude, y = Latitude)) +
#scale_alpha(range = c(0, 0.3), guide = FALSE) +
  xlab("") + ylab("") +
  plot_theme(
    legend.key = element_blank(),
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    legend.position = 'top',
    panel.border = element_rect(colour = "black", fill = "NA", size = .5))

#All strandings heatmap
ggmap(get_map(location = box, source = "osm")) +
  geom_point(data = pinnipeds.data, aes(x = Longitude, y = Latitude))  +
  stat_density2d(data = pinnipeds.data, aes(x = Longitude, y = Latitude, fill = ..level.., alpha = ..level..), size = 0.01, bins = 100, geom = "polygon") +

  scale_fill_gradient(low = "yellow", high = "red", guide = FALSE) +
  scale_alpha(range = c(0, 0.3), guide = FALSE) +
  xlab("") + ylab("") +
  theme(
    axis.ticks = element_blank(),
    axis.text = element_blank())

#Puget sound heatmap - all strandings
ggmap(get_map(location = "Puget Sound", source = "stamen", maptype = "watercolor")) +
  geom_point(data = pinnipeds.data, aes(x = Longitude, y = Latitude))  +
  stat_density2d(data = pinnipeds.data, aes(x = Longitude, y = Latitude, fill = ..level.., alpha = ..level..), size = 0.01, bins = 100, geom = "polygon") +

  scale_fill_gradient(low = "yellow", high = "red", guide = FALSE) +
  scale_alpha(range = c(0, 0.1), guide = FALSE) +
  xlab("") + ylab("") +
  theme(
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    panel.border = element_rect(colour = "black", fill = "NA", size = .5))

#Oregon coast heatmap - all strandings
ggmap(get_map(location = c(-123.627933, 44.163370), source = "google", maptype = "roadmap", zoom = 7)) +
  geom_point(data = pinnipeds.data, aes(x = Longitude, y = Latitude))  +
  stat_density2d(data = pinnipeds.data, aes(x = Longitude, y = Latitude, fill = ..level.., alpha = ..level..), size = 0.01, bins = 60, geom = "polygon") +

  scale_fill_gradient(low = "yellow", high = "red", guide = FALSE) +
  scale_alpha(range = c(0, 0.3), guide = FALSE)

#Human interactions - dots by HI type
pinniped.HI.map.data <- pinnipeds.data %>% filter(Findings.of.Human.Interaction == 'Y' & Interaction.Type != 'NA')

ggmap(get_map(location = box, source = "osm")) +
  geom_point(data = pinniped.HI.map.data, aes(x = Longitude, y = Latitude, color = Interaction.Type)) +
scale_alpha(range = c(0, 0.3), guide = FALSE) +
  xlab("") + ylab("") +
  plot_theme(
    legend.key = element_blank(),
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    legend.position = 'top',
    panel.border = element_rect(colour = "black", fill = "NA", size = .5))

```

