---
title: "Project Notes"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Helpful readme on regression methods: http://www.statmethods.net/stats/regression.html

##Methodological Questions

- What are the things I should be cognizant of that are particular to my data? 
- How to deal with colinearity of oceanographic conditions, and seasonality of all strandings?
- How will the models deal with certain oceanographic variables not being available for the whole time series?

##To Dos
- Learn about rgdal package
- Jenn wants arrow on maps for North
- Y/N stranding network member rates
- read multivariate/backwards
- stats table update?
- explore satScan
- Spearman and Kendall rank test; Vuong test
- Maps: kernel density: overall vs. LN/EN; satscan: overall as background, LN/EN
- Get inland buoy data?
- Derive lags: 6, mixed, fixed
- Menza et al 2016 for local harbor seal abundance?
- Consider CAR package? https://cran.r-project.org/web/packages/car/index.html 

##Project Activities Log

- 4/10/17: separated data compiling into separate cleaning script
- 4/14/17: created ENSO stranding stats Rmd
